// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjjapiuGF_hb_Thj6hX5UbvEqOoQ8iYQE',
    appId: '1:767588494857:web:18d231bee8d6bfe55252d8',
    messagingSenderId: '767588494857',
    projectId: 'chegaja-ac88d',
    authDomain: 'chegaja-ac88d.firebaseapp.com',
    storageBucket: 'chegaja-ac88d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfLgIdf5fJ_wnFbLuB_So8oX9JpgM-7Og',
    appId: '1:767588494857:android:f31e72877260a7555252d8',
    messagingSenderId: '767588494857',
    projectId: 'chegaja-ac88d',
    storageBucket: 'chegaja-ac88d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyxboTkz8qvykhNo6fDYBu3Rd0Rdm7hs8',
    appId: '1:767588494857:ios:46bc77e492b3ddac5252d8',
    messagingSenderId: '767588494857',
    projectId: 'chegaja-ac88d',
    storageBucket: 'chegaja-ac88d.firebasestorage.app',
    iosClientId: '767588494857-7ihke0eqsj1jmm99hbp61iu666s6058m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chegajaV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyxboTkz8qvykhNo6fDYBu3Rd0Rdm7hs8',
    appId: '1:767588494857:ios:46bc77e492b3ddac5252d8',
    messagingSenderId: '767588494857',
    projectId: 'chegaja-ac88d',
    storageBucket: 'chegaja-ac88d.firebasestorage.app',
    iosClientId: '767588494857-7ihke0eqsj1jmm99hbp61iu666s6058m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chegajaV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjjapiuGF_hb_Thj6hX5UbvEqOoQ8iYQE',
    appId: '1:767588494857:web:097c76c90ddb767a5252d8',
    messagingSenderId: '767588494857',
    projectId: 'chegaja-ac88d',
    authDomain: 'chegaja-ac88d.firebaseapp.com',
    storageBucket: 'chegaja-ac88d.firebasestorage.app',
  );
}
