/// Lista inicial grande de serviços (categorias) para o ChegaJá.
/// Cada item corresponde a um documento em `servicos/{id}`.
final initialServicos = <Map<String, dynamic>>[
  // ==========================
  // CASA & REPARAÇÕES
  // ==========================
  {
    'id': 'canalizador',
    'name': 'Canalizador',
    'mode': 'IMEDIATO',
    'keywords': ['canalizador', 'água', 'fuga', 'torneira', 'cano'],
    'iconKey': 'canalizador',
    'isActive': true,
  },
  {
    'id': 'eletricista',
    'name': 'Eletricista',
    'mode': 'IMEDIATO',
    'keywords': ['eletricista', 'luz', 'tomada', 'quadro', 'curto-circuito'],
    'iconKey': 'eletricista',
    'isActive': true,
  },
  {
    'id': 'pedreiro',
    'name': 'Pedreiro',
    'mode': 'POR_PROPOSTA',
    'keywords': ['pedreiro', 'obra', 'paredes', 'reboco', 'construção'],
    'iconKey': 'pedreiro',
    'isActive': true,
  },
  {
    'id': 'pintor',
    'name': 'Pintor',
    'mode': 'POR_PROPOSTA',
    'keywords': ['pintor', 'pintura', 'paredes', 'tinta'],
    'iconKey': 'pintor',
    'isActive': true,
  },
  {
    'id': 'serralheiro',
    'name': 'Serralheiro',
    'mode': 'IMEDIATO',
    'keywords': ['serralheiro', 'porta', 'grade', 'ferro', 'fechadura'],
    'iconKey': 'serralheiro',
    'isActive': true,
  },
  {
    'id': 'carpinteiro',
    'name': 'Carpinteiro',
    'mode': 'POR_PROPOSTA',
    'keywords': ['carpinteiro', 'madeira', 'móveis', 'armário'],
    'iconKey': 'carpinteiro',
    'isActive': true,
  },
  {
    'id': 'montagem_moveis',
    'name': 'Montagem de móveis',
    'mode': 'AGENDADO',
    'keywords': ['montagem', 'móveis', 'ikea', 'armário', 'prateleira'],
    'iconKey': 'montagem_moveis',
    'isActive': true,
  },
  {
    'id': 'manutencao_geral',
    'name': 'Manutenção geral / Faz-tudo',
    'mode': 'IMEDIATO',
    'keywords': ['manutenção', 'faz-tudo', 'reparos', 'pequenas obras'],
    'iconKey': 'handyman',
    'isActive': true,
  },
  {
    'id': 'vidraceiro',
    'name': 'Vidraceiro',
    'mode': 'IMEDIATO',
    'keywords': ['vidro', 'janela', 'porta de vidro', 'vidraceiro'],
    'iconKey': 'vidraceiro',
    'isActive': true,
  },
  {
    'id': 'climatizacao',
    'name': 'Climatização / AC',
    'mode': 'AGENDADO',
    'keywords': [
      'ar condicionado',
      'climatização',
      'instalação',
      'manutenção',
    ],
    'iconKey': 'climatizacao',
    'isActive': true,
  },
  {
    'id': 'instalacao_solar',
    'name': 'Painéis solares',
    'mode': 'POR_PROPOSTA',
    'keywords': ['solar', 'painéis', 'energia', 'instalação'],
    'iconKey': 'instalacao_solar',
    'isActive': true,
  },
  {
    'id': 'inspecao_casas',
    'name': 'Inspeção de casas',
    'mode': 'AGENDADO',
    'keywords': ['inspeção', 'casa', 'imóvel', 'relatório técnico'],
    'iconKey': 'inspecao_casas',
    'isActive': true,
  },

  // LIMPEZA & ORGANIZAÇÃO
  {
    'id': 'limpeza_domestica',
    'name': 'Limpeza doméstica',
    'mode': 'AGENDADO',
    'keywords': ['limpeza', 'casa', 'faxina', 'doméstica'],
    'iconKey': 'limpeza_domestica',
    'isActive': true,
  },
  {
    'id': 'limpeza_profunda',
    'name': 'Limpeza profunda',
    'mode': 'AGENDADO',
    'keywords': ['limpeza profunda', 'cozinha', 'casa de banho'],
    'iconKey': 'limpeza_profunda',
    'isActive': true,
  },
  {
    'id': 'limpeza_pos_obra',
    'name': 'Limpeza pós-obra',
    'mode': 'POR_PROPOSTA',
    'keywords': ['limpeza', 'pós-obra', 'obra', 'reforma', 'construção'],
    'iconKey': 'limpeza_pos_obra',
    'isActive': true,
  },
  {
    'id': 'limpeza_comercial',
    'name': 'Limpeza de escritórios / lojas',
    'mode': 'AGENDADO',
    'keywords': ['limpeza', 'escritório', 'loja', 'comercial'],
    'iconKey': 'limpeza_comercial',
    'isActive': true,
  },
  {
    'id': 'limpeza_vidros',
    'name': 'Limpeza de vidros / janelas',
    'mode': 'AGENDADO',
    'keywords': ['limpeza', 'vidros', 'janelas', 'fachada'],
    'iconKey': 'limpeza_vidros',
    'isActive': true,
  },
  {
    'id': 'lavandaria',
    'name': 'Lavandaria / Passar roupa',
    'mode': 'AGENDADO',
    'keywords': ['lavar roupa', 'lavandaria', 'passar roupa'],
    'iconKey': 'lavandaria',
    'isActive': true,
  },
  {
    'id': 'organizacao_casas',
    'name': 'Organização de casas',
    'mode': 'AGENDADO',
    'keywords': ['organização', 'arrumação', 'destralhar', 'closet'],
    'iconKey': 'organizacao_casas',
    'isActive': true,
  },
  {
    'id': 'jardinagem',
    'name': 'Jardinagem',
    'mode': 'AGENDADO',
    'keywords': ['jardim', 'jardinagem', 'relvado', 'árvores', 'plantas'],
    'iconKey': 'jardinagem',
    'isActive': true,
  },
  {
    'id': 'paisagismo',
    'name': 'Paisagismo',
    'mode': 'POR_PROPOSTA',
    'keywords': ['paisagismo', 'jardins', 'projeto', 'exterior'],
    'iconKey': 'paisagismo',
    'isActive': true,
  },
  {
    'id': 'piscinas',
    'name': 'Limpeza e manutenção de piscinas',
    'mode': 'AGENDADO',
    'keywords': ['piscina', 'limpeza', 'manutenção'],
    'iconKey': 'piscinas',
    'isActive': true,
  },

  // AUTO & TRANSPORTE
  {
    'id': 'mecanico',
    'name': 'Mecânico',
    'mode': 'IMEDIATO',
    'keywords': ['mecânico', 'carro', 'motor', 'avaria'],
    'iconKey': 'mecanico',
    'isActive': true,
  },
  {
    'id': 'eletricista_auto',
    'name': 'Eletricista auto',
    'mode': 'AGENDADO',
    'keywords': ['eletricista auto', 'bateria', 'luzes carro'],
    'iconKey': 'eletricista_auto',
    'isActive': true,
  },
  {
    'id': 'lavagem_auto',
    'name': 'Lavagem auto',
    'mode': 'AGENDADO',
    'keywords': ['lavagem', 'carro', 'auto', 'limpeza carro'],
    'iconKey': 'lavagem_auto',
    'isActive': true,
  },
  {
    'id': 'detalhe_auto',
    'name': 'Detalhe automóvel / Polimento',
    'mode': 'AGENDADO',
    'keywords': ['detalhe', 'polimento', 'carro', 'detailing'],
    'iconKey': 'detalhe_auto',
    'isActive': true,
  },
  {
    'id': 'reboque',
    'name': 'Reboque',
    'mode': 'IMEDIATO',
    'keywords': ['reboque', 'guincho', 'avaria', 'acidente'],
    'iconKey': 'reboque',
    'isActive': true,
  },
  {
    'id': 'motorista_privado',
    'name': 'Motorista privado',
    'mode': 'AGENDADO',
    'keywords': ['motorista', 'transporte', 'privado'],
    'iconKey': 'motorista_privado',
    'isActive': true,
  },
  {
    'id': 'entregas_moto',
    'name': 'Entregas de moto / courier',
    'mode': 'IMEDIATO',
    'keywords': ['entregas', 'moto', 'courier', 'delivery'],
    'iconKey': 'entregas_moto',
    'isActive': true,
  },

  // BELEZA & BEM-ESTAR
  {
    'id': 'cabeleireiro',
    'name': 'Cabeleireiro / Barber',
    'mode': 'AGENDADO',
    'keywords': ['cabeleireiro', 'barbeiro', 'corte', 'penteado'],
    'iconKey': 'cabeleireiro',
    'isActive': true,
  },
  {
    'id': 'manicure_pedicure',
    'name': 'Manicure / Pedicure',
    'mode': 'AGENDADO',
    'keywords': ['unhas', 'manicure', 'pedicure', 'gel'],
    'iconKey': 'manicure_pedicure',
    'isActive': true,
  },
  {
    'id': 'maquilhagem',
    'name': 'Maquilhadora / Makeup artist',
    'mode': 'AGENDADO',
    'keywords': ['maquilhagem', 'makeup', 'noiva', 'evento'],
    'iconKey': 'maquilhagem',
    'isActive': true,
  },
  {
    'id': 'estetica',
    'name': 'Estética / Spa',
    'mode': 'AGENDADO',
    'keywords': ['estética', 'spa', 'limpeza de pele', 'tratamento'],
    'iconKey': 'estetica',
    'isActive': true,
  },
  {
    'id': 'massagista',
    'name': 'Massagista',
    'mode': 'AGENDADO',
    'keywords': ['massagem', 'massagista', 'relaxamento', 'tensão'],
    'iconKey': 'massagista',
    'isActive': true,
  },
  {
    'id': 'personal_trainer',
    'name': 'Personal Trainer',
    'mode': 'AGENDADO',
    'keywords': ['personal trainer', 'treino', 'ginásio', 'fitness'],
    'iconKey': 'personal_trainer',
    'isActive': true,
  },
  {
    'id': 'instrutor_yoga',
    'name': 'Instrutor de Yoga',
    'mode': 'AGENDADO',
    'keywords': ['yoga', 'bem-estar', 'alongamento', 'relaxamento'],
    'iconKey': 'instrutor_yoga',
    'isActive': true,
  },
  {
    'id': 'instrutor_pilates',
    'name': 'Instrutor de Pilates',
    'mode': 'AGENDADO',
    'keywords': ['pilates', 'corpo', 'postura', 'exercício'],
    'iconKey': 'instrutor_pilates',
    'isActive': true,
  },
  {
    'id': 'nutricionista',
    'name': 'Nutricionista',
    'mode': 'AGENDADO',
    'keywords': ['nutrição', 'nutricionista', 'dieta', 'alimentação'],
    'iconKey': 'nutricionista',
    'isActive': true,
  },
  {
    'id': 'coach_vida',
    'name': 'Coach de vida / Desenvolvimento pessoal',
    'mode': 'AGENDADO',
    'keywords': ['coach', 'vida', 'desenvolvimento pessoal', 'objetivos'],
    'iconKey': 'coach_vida',
    'isActive': true,
  },

  // CUIDADOS & FAMÍLIA
  {
    'id': 'babysitter',
    'name': 'Babysitter',
    'mode': 'AGENDADO',
    'keywords': ['babysitter', 'crianças', 'cuidar', 'noite'],
    'iconKey': 'babysitter',
    'isActive': true,
  },
  {
    'id': 'cuidador_idosos',
    'name': 'Cuidador de idosos',
    'mode': 'AGENDADO',
    'keywords': ['idosos', 'cuidador', 'companheiro', 'ajuda'],
    'iconKey': 'cuidador_idosos',
    'isActive': true,
  },
  {
    'id': 'apoio_domestico',
    'name': 'Empregada doméstica / apoio total',
    'mode': 'AGENDADO',
    'keywords': ['doméstica', 'apoio', 'casa', 'serviço doméstico'],
    'iconKey': 'apoio_domestico',
    'isActive': true,
  },
  {
    'id': 'daycare',
    'name': 'Creche / Daycare (informal)',
    'mode': 'AGENDADO',
    'keywords': ['creche', 'daycare', 'crianças', 'cuidar'],
    'iconKey': 'daycare',
    'isActive': true,
  },

  // PETS
  {
    'id': 'cuidador_cao',
    'name': 'Cuidador de cão / Pet sitter',
    'mode': 'AGENDADO',
    'keywords': ['cães', 'pets', 'cuidador', 'pet sitter'],
    'iconKey': 'cuidador_cao',
    'isActive': true,
  },
  {
    'id': 'dogwalker',
    'name': 'Dog walker',
    'mode': 'IMEDIATO',
    'keywords': ['dog walker', 'passear cão', 'caminhada'],
    'iconKey': 'dogwalker',
    'isActive': true,
  },
  {
    'id': 'banho_tosa',
    'name': 'Banho e tosa',
    'mode': 'AGENDADO',
    'keywords': ['banho', 'tosa', 'pets', 'cães'],
    'iconKey': 'banho_tosa',
    'isActive': true,
  },
  {
    'id': 'treinador_caes',
    'name': 'Treinador de cães',
    'mode': 'AGENDADO',
    'keywords': ['treinar cão', 'obediência', 'pets'],
    'iconKey': 'treinador_caes',
    'isActive': true,
  },

  // EDUCAÇÃO & AULAS
  {
    'id': 'explicador',
    'name': 'Explicador / Aulas particulares',
    'mode': 'AGENDADO',
    'keywords': ['explicador', 'aulas', 'estudo', 'reforço escolar'],
    'iconKey': 'explicador',
    'isActive': true,
  },
  {
    'id': 'aulas_matematica',
    'name': 'Aulas de Matemática',
    'mode': 'AGENDADO',
    'keywords': ['matemática', 'explicações', 'aulas', 'cálculo'],
    'iconKey': 'aulas_matematica',
    'isActive': true,
  },
  {
    'id': 'aulas_idiomas',
    'name': 'Aulas de idiomas',
    'mode': 'AGENDADO',
    'keywords': ['inglês', 'idiomas', 'línguas', 'aulas'],
    'iconKey': 'aulas_idiomas',
    'isActive': true,
  },
  {
    'id': 'aulas_musica',
    'name': 'Aulas de música',
    'mode': 'AGENDADO',
    'keywords': ['música', 'guitarra', 'piano', 'voz'],
    'iconKey': 'aulas_musica',
    'isActive': true,
  },
  {
    'id': 'explicacoes_universitarias',
    'name': 'Explicações universitárias',
    'mode': 'AGENDADO',
    'keywords': ['universidade', 'explicações', 'cadeiras', 'exames'],
    'iconKey': 'explicacoes_universitarias',
    'isActive': true,
  },

  // DIGITAL & CRIATIVO
  {
    'id': 'designer_grafico',
    'name': 'Designer gráfico',
    'mode': 'POR_PROPOSTA',
    'keywords': ['design', 'logo', 'flyer', 'cartaz'],
    'iconKey': 'designer_grafico',
    'isActive': true,
  },
  {
    'id': 'ilustrador',
    'name': 'Ilustrador / Artista digital',
    'mode': 'POR_PROPOSTA',
    'keywords': ['ilustração', 'desenho', 'retrato', 'arte digital'],
    'iconKey': 'ilustrador',
    'isActive': true,
  },
  {
    'id': 'fotografo',
    'name': 'Fotógrafo',
    'mode': 'POR_PROPOSTA',
    'keywords': ['fotografia', 'sessão', 'casamento', 'evento'],
    'iconKey': 'fotografo',
    'isActive': true,
  },
  {
    'id': 'videomaker',
    'name': 'Videomaker',
    'mode': 'POR_PROPOSTA',
    'keywords': ['vídeo', 'filmagem', 'edição', 'evento'],
    'iconKey': 'videomaker',
    'isActive': true,
  },
  {
    'id': 'editor_video',
    'name': 'Editor de vídeo',
    'mode': 'POR_PROPOSTA',
    'keywords': ['edição', 'vídeo', 'conteúdo', 'youtube'],
    'iconKey': 'editor_video',
    'isActive': true,
  },
  {
    'id': 'social_media',
    'name': 'Gestor de redes sociais',
    'mode': 'POR_PROPOSTA',
    'keywords': ['social media', 'instagram', 'facebook', 'marketing'],
    'iconKey': 'social_media',
    'isActive': true,
  },
  {
    'id': 'copywriter',
    'name': 'Copywriter / Redator',
    'mode': 'POR_PROPOSTA',
    'keywords': ['copywriting', 'redação', 'texto', 'conteúdo'],
    'iconKey': 'copywriter',
    'isActive': true,
  },
  {
    'id': 'web_designer',
    'name': 'Web designer',
    'mode': 'POR_PROPOSTA',
    'keywords': ['web design', 'website', 'landing page'],
    'iconKey': 'web_designer',
    'isActive': true,
  },
  {
    'id': 'programador',
    'name': 'Programador / Desenvolvedor',
    'mode': 'POR_PROPOSTA',
    'keywords': ['programador', 'app', 'website', 'software'],
    'iconKey': 'programador',
    'isActive': true,
  },
  {
    'id': 'seo_specialist',
    'name': 'Especialista em SEO',
    'mode': 'POR_PROPOSTA',
    'keywords': ['SEO', 'google', 'busca', 'otimização'],
    'iconKey': 'seo_specialist',
    'isActive': true,
  },
  {
    'id': 'ads_manager',
    'name': 'Gestor de anúncios (Google/Facebook Ads)',
    'mode': 'POR_PROPOSTA',
    'keywords': ['anúncios', 'ads', 'tráfego pago', 'google ads'],
    'iconKey': 'ads_manager',
    'isActive': true,
  },
  {
    'id': 'tradutor',
    'name': 'Tradutor / Intérprete',
    'mode': 'POR_PROPOSTA',
    'keywords': ['tradução', 'intérprete', 'idiomas'],
    'iconKey': 'tradutor',
    'isActive': true,
  },

  // NEGÓCIOS & CONSULTORIA
  {
    'id': 'consultor_negocios',
    'name': 'Consultor de negócios',
    'mode': 'POR_PROPOSTA',
    'keywords': ['consultoria', 'negócios', 'empresa', 'estratégia'],
    'iconKey': 'consultor_negocios',
    'isActive': true,
  },
  {
    'id': 'consultor_financeiro',
    'name': 'Consultor financeiro',
    'mode': 'POR_PROPOSTA',
    'keywords': ['finanças', 'consultoria', 'investimento', 'planeamento'],
    'iconKey': 'consultor_financeiro',
    'isActive': true,
  },
  {
    'id': 'contabilista',
    'name': 'Contabilista / Accountant',
    'mode': 'POR_PROPOSTA',
    'keywords': ['contabilidade', 'impostos', 'declarações'],
    'iconKey': 'contabilista',
    'isActive': true,
  },
  {
    'id': 'assistente_virtual',
    'name': 'Assistente virtual',
    'mode': 'AGENDADO',
    'keywords': ['assistente virtual', 'tarefas', 'administração'],
    'iconKey': 'assistente_virtual',
    'isActive': true,
  },
  {
    'id': 'recrutamento',
    'name': 'Recrutamento / RH',
    'mode': 'POR_PROPOSTA',
    'keywords': ['recrutamento', 'RH', 'emprego', 'entrevistas'],
    'iconKey': 'recrutamento',
    'isActive': true,
  },
  {
    'id': 'consultor_imobiliario',
    'name': 'Consultor imobiliário',
    'mode': 'AGENDADO',
    'keywords': ['imobiliário', 'casas', 'aluguer', 'comprar'],
    'iconKey': 'consultor_imobiliario',
    'isActive': true,
  },
  {
    'id': 'consultor_migracao',
    'name': 'Consultor de migração / vistos',
    'mode': 'AGENDADO',
    'keywords': ['vistos', 'migração', 'documentos', 'legal'],
    'iconKey': 'consultor_migracao',
    'isActive': true,
  },

  // EVENTOS & FESTAS
  {
    'id': 'confeitaria',
    'name': 'Confeitaria / Bolos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['bolo', 'doces', 'cake', 'aniversário', 'casamento'],
    'iconKey': 'confeitaria',
    'isActive': true,
  },
  {
    'id': 'catering',
    'name': 'Catering / Comida para eventos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['catering', 'buffet', 'evento', 'comida'],
    'iconKey': 'catering',
    'isActive': true,
  },
  {
    'id': 'decorador_eventos',
    'name': 'Decorador de eventos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['decoração', 'eventos', 'casamento', 'festa'],
    'iconKey': 'decorador_eventos',
    'isActive': true,
  },
  {
    'id': 'dj',
    'name': 'DJ / Música para eventos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['dj', 'música', 'evento', 'festa'],
    'iconKey': 'dj',
    'isActive': true,
  },
  {
    'id': 'animador_festas',
    'name': 'Animador de festas',
    'mode': 'AGENDADO',
    'keywords': ['animador', 'festas', 'crianças', 'animação'],
    'iconKey': 'animador_festas',
    'isActive': true,
  },
  {
    'id': 'planeador_casamentos',
    'name': 'Wedding planner / Planeador de casamentos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['casamento', 'wedding planner', 'evento'],
    'iconKey': 'planeador_casamentos',
    'isActive': true,
  },
  {
    'id': 'planeador_eventos',
    'name': 'Planeador de eventos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['eventos', 'planeamento', 'festas', 'corporativo'],
    'iconKey': 'planeador_eventos',
    'isActive': true,
  },

  // OUTROS / GERAIS
  {
    'id': 'consultor_tecnologia',
    'name': 'Consultor de tecnologia / IT',
    'mode': 'POR_PROPOSTA',
    'keywords': ['IT', 'tecnologia', 'sistemas', 'infraestrutura'],
    'iconKey': 'consultor_tecnologia',
    'isActive': true,
  },
  {
    'id': 'suporte_informatica',
    'name': 'Suporte de informática / Reparação PC',
    'mode': 'AGENDADO',
    'keywords': ['computador', 'suporte', 'reparação', 'PC'],
    'iconKey': 'suporte_informatica',
    'isActive': true,
  },
  {
    'id': 'seguranca_eventos',
    'name': 'Segurança para eventos',
    'mode': 'AGENDADO',
    'keywords': ['segurança', 'evento', 'vigilante'],
    'iconKey': 'seguranca_eventos',
    'isActive': true,
  },
  {
    'id': 'costureira',
    'name': 'Costureira / Ajustes de roupa',
    'mode': 'AGENDADO',
    'keywords': ['costura', 'ajustes', 'roupa', 'baínha'],
    'iconKey': 'costureira',
    'isActive': true,
  },
  {
    'id': 'reparacao_calcado',
    'name': 'Reparação de calçado',
    'mode': 'AGENDADO',
    'keywords': ['sapatos', 'reparação', 'calçado'],
    'iconKey': 'reparacao_calcado',
    'isActive': true,
  },
];
