/// Lista inicial grande de serviços (categorias) para o ChegaJá.
/// Cada item corresponde a um documento em `servicos/{id}`.
final initialServicos = <Map<String, dynamic>>[
  // ==========================
  // CASA & REPARAÇÕES
  // ==========================
  {
    'id': 'canalizador',
    'name': 'Canalizador',
    'mode': 'IMEDIATO',
    'keywords': ['canalizador', 'água', 'fuga', 'torneira', 'cano'],
    'iconKey': 'canalizador',
    'isActive': true,
  },
  {
    'id': 'eletricista',
    'name': 'Eletricista',
    'mode': 'IMEDIATO',
    'keywords': ['eletricista', 'luz', 'tomada', 'quadro', 'curto-circuito'],
    'iconKey': 'eletricista',
    'isActive': true,
  },
  {
    'id': 'pedreiro',
    'name': 'Pedreiro',
    'mode': 'POR_PROPOSTA',
    'keywords': ['pedreiro', 'obra', 'paredes', 'reboco', 'construção'],
    'iconKey': 'pedreiro',
    'isActive': true,
  },
  {
    'id': 'pintor',
    'name': 'Pintor',
    'mode': 'POR_PROPOSTA',
    'keywords': ['pintor', 'pintura', 'paredes', 'tinta'],
    'iconKey': 'pintor',
    'isActive': true,
  },
  {
    'id': 'serralheiro',
    'name': 'Serralheiro',
    'mode': 'IMEDIATO',
    'keywords': ['serralheiro', 'porta', 'grade', 'ferro', 'fechadura'],
    'iconKey': 'serralheiro',
    'isActive': true,
  },
  {
    'id': 'carpinteiro',
    'name': 'Carpinteiro',
    'mode': 'POR_PROPOSTA',
    'keywords': ['carpinteiro', 'madeira', 'móveis', 'armário'],
    'iconKey': 'carpinteiro',
    'isActive': true,
  },
  {
    'id': 'montagem_moveis',
    'name': 'Montagem de móveis',
    'mode': 'AGENDADO',
    'keywords': ['montagem', 'móveis', 'ikea', 'armário', 'prateleira'],
    'iconKey': 'montagem_moveis',
    'isActive': true,
  },
  {
    'id': 'manutencao_geral',
    'name': 'Manutenção geral / Faz-tudo',
    'mode': 'IMEDIATO',
    'keywords': ['manutenção', 'faz-tudo', 'reparos', 'pequenas obras'],
    'iconKey': 'handyman',
    'isActive': true,
  },
  {
    'id': 'vidraceiro',
    'name': 'Vidraceiro',
    'mode': 'IMEDIATO',
    'keywords': ['vidro', 'janela', 'porta de vidro', 'vidraceiro'],
    'iconKey': 'vidraceiro',
    'isActive': true,
  },
  {
    'id': 'climatizacao',
    'name': 'Climatização / AC',
    'mode': 'AGENDADO',
    'keywords': [
      'ar condicionado',
      'climatização',
      'instalação',
      'manutenção',
    ],
    'iconKey': 'climatizacao',
    'isActive': true,
  },
  {
    'id': 'instalacao_solar',
    'name': 'Painéis solares',
    'mode': 'POR_PROPOSTA',
    'keywords': ['solar', 'painéis', 'energia', 'instalação'],
    'iconKey': 'instalacao_solar',
    'isActive': true,
  },
  {
    'id': 'inspecao_casas',
    'name': 'Inspeção de casas',
    'mode': 'AGENDADO',
    'keywords': ['inspeção', 'casa', 'imóvel', 'relatório técnico'],
    'iconKey': 'inspecao_casas',
    'isActive': true,
  },

  // LIMPEZA & ORGANIZAÇÃO
  {
    'id': 'limpeza_domestica',
    'name': 'Limpeza doméstica',
    'mode': 'AGENDADO',
    'keywords': ['limpeza', 'casa', 'faxina', 'doméstica'],
    'iconKey': 'limpeza_domestica',
    'isActive': true,
  },
  {
    'id': 'limpeza_profunda',
    'name': 'Limpeza profunda',
    'mode': 'AGENDADO',
    'keywords': ['limpeza profunda', 'cozinha', 'casa de banho'],
    'iconKey': 'limpeza_profunda',
    'isActive': true,
  },
  {
    'id': 'limpeza_pos_obra',
    'name': 'Limpeza pós-obra',
    'mode': 'POR_PROPOSTA',
    'keywords': ['limpeza', 'pós-obra', 'obra', 'reforma', 'construção'],
    'iconKey': 'limpeza_pos_obra',
    'isActive': true,
  },
  {
    'id': 'limpeza_comercial',
    'name': 'Limpeza de escritórios / lojas',
    'mode': 'AGENDADO',
    'keywords': ['limpeza', 'escritório', 'loja', 'comercial'],
    'iconKey': 'limpeza_comercial',
    'isActive': true,
  },
  {
    'id': 'limpeza_vidros',
    'name': 'Limpeza de vidros / janelas',
    'mode': 'AGENDADO',
    'keywords': ['limpeza', 'vidros', 'janelas', 'fachada'],
    'iconKey': 'limpeza_vidros',
    'isActive': true,
  },
  {
    'id': 'lavandaria',
    'name': 'Lavandaria / Passar roupa',
    'mode': 'AGENDADO',
    'keywords': ['lavar roupa', 'lavandaria', 'passar roupa'],
    'iconKey': 'lavandaria',
    'isActive': true,
  },
  {
    'id': 'organizacao_casas',
    'name': 'Organização de casas',
    'mode': 'AGENDADO',
    'keywords': ['organização', 'arrumação', 'destralhar', 'closet'],
    'iconKey': 'organizacao_casas',
    'isActive': true,
  },
  {
    'id': 'jardinagem',
    'name': 'Jardinagem',
    'mode': 'AGENDADO',
    'keywords': ['jardim', 'jardinagem', 'relvado', 'árvores', 'plantas'],
    'iconKey': 'jardinagem',
    'isActive': true,
  },
  {
    'id': 'paisagismo',
    'name': 'Paisagismo',
    'mode': 'POR_PROPOSTA',
    'keywords': ['paisagismo', 'jardins', 'projeto', 'exterior'],
    'iconKey': 'paisagismo',
    'isActive': true,
  },
  {
    'id': 'piscinas',
    'name': 'Limpeza e manutenção de piscinas',
    'mode': 'AGENDADO',
    'keywords': ['piscina', 'limpeza', 'manutenção'],
    'iconKey': 'piscinas',
    'isActive': true,
  },

  // AUTO & TRANSPORTE
  {
    'id': 'mecanico',
    'name': 'Mecânico',
    'mode': 'IMEDIATO',
    'keywords': ['mecânico', 'carro', 'motor', 'avaria'],
    'iconKey': 'mecanico',
    'isActive': true,
  },
  {
    'id': 'eletricista_auto',
    'name': 'Eletricista auto',
    'mode': 'AGENDADO',
    'keywords': ['eletricista auto', 'bateria', 'luzes carro'],
    'iconKey': 'eletricista_auto',
    'isActive': true,
  },
  {
    'id': 'lavagem_auto',
    'name': 'Lavagem auto',
    'mode': 'AGENDADO',
    'keywords': ['lavagem', 'carro', 'auto', 'limpeza carro'],
    'iconKey': 'lavagem_auto',
    'isActive': true,
  },
  {
    'id': 'detalhe_auto',
    'name': 'Detalhe automóvel / Polimento',
    'mode': 'AGENDADO',
    'keywords': ['detalhe', 'polimento', 'carro', 'detailing'],
    'iconKey': 'detalhe_auto',
    'isActive': true,
  },
  {
    'id': 'reboque',
    'name': 'Reboque',
    'mode': 'IMEDIATO',
    'keywords': ['reboque', 'guincho', 'avaria', 'acidente'],
    'iconKey': 'reboque',
    'isActive': true,
  },
  {
    'id': 'motorista_privado',
    'name': 'Motorista privado',
    'mode': 'AGENDADO',
    'keywords': ['motorista', 'transporte', 'privado'],
    'iconKey': 'motorista_privado',
    'isActive': true,
  },
  {
    'id': 'entregas_moto',
    'name': 'Entregas de moto / courier',
    'mode': 'IMEDIATO',
    'keywords': ['entregas', 'moto', 'courier', 'delivery'],
    'iconKey': 'entregas_moto',
    'isActive': true,
  },

  // BELEZA & BEM-ESTAR
  {
    'id': 'cabeleireiro',
    'name': 'Cabeleireiro / Barber',
    'mode': 'AGENDADO',
    'keywords': ['cabeleireiro', 'barbeiro', 'corte', 'penteado'],
    'iconKey': 'cabeleireiro',
    'isActive': true,
  },
  {
    'id': 'manicure_pedicure',
    'name': 'Manicure / Pedicure',
    'mode': 'AGENDADO',
    'keywords': ['unhas', 'manicure', 'pedicure', 'gel'],
    'iconKey': 'manicure_pedicure',
    'isActive': true,
  },
  {
    'id': 'maquilhagem',
    'name': 'Maquilhadora / Makeup artist',
    'mode': 'AGENDADO',
    'keywords': ['maquilhagem', 'makeup', 'noiva', 'evento'],
    'iconKey': 'maquilhagem',
    'isActive': true,
  },
  {
    'id': 'estetica',
    'name': 'Estética / Spa',
    'mode': 'AGENDADO',
    'keywords': ['estética', 'spa', 'limpeza de pele', 'tratamento'],
    'iconKey': 'estetica',
    'isActive': true,
  },
  {
    'id': 'massagista',
    'name': 'Massagista',
    'mode': 'AGENDADO',
    'keywords': ['massagem', 'massagista', 'relaxamento', 'tensão'],
    'iconKey': 'massagista',
    'isActive': true,
  },
  {
    'id': 'personal_trainer',
    'name': 'Personal Trainer',
    'mode': 'AGENDADO',
    'keywords': ['personal trainer', 'treino', 'ginásio', 'fitness'],
    'iconKey': 'personal_trainer',
    'isActive': true,
  },
  {
    'id': 'instrutor_yoga',
    'name': 'Instrutor de Yoga',
    'mode': 'AGENDADO',
    'keywords': ['yoga', 'bem-estar', 'alongamento', 'relaxamento'],
    'iconKey': 'instrutor_yoga',
    'isActive': true,
  },
  {
    'id': 'instrutor_pilates',
    'name': 'Instrutor de Pilates',
    'mode': 'AGENDADO',
    'keywords': ['pilates', 'corpo', 'postura', 'exercício'],
    'iconKey': 'instrutor_pilates',
    'isActive': true,
  },
  {
    'id': 'nutricionista',
    'name': 'Nutricionista',
    'mode': 'AGENDADO',
    'keywords': ['nutrição', 'nutricionista', 'dieta', 'alimentação'],
    'iconKey': 'nutricionista',
    'isActive': true,
  },
  {
    'id': 'coach_vida',
    'name': 'Coach de vida / Desenvolvimento pessoal',
    'mode': 'AGENDADO',
    'keywords': ['coach', 'vida', 'desenvolvimento pessoal', 'objetivos'],
    'iconKey': 'coach_vida',
    'isActive': true,
  },

  // CUIDADOS & FAMÍLIA
  {
    'id': 'babysitter',
    'name': 'Babysitter',
    'mode': 'AGENDADO',
    'keywords': ['babysitter', 'crianças', 'cuidar', 'noite'],
    'iconKey': 'babysitter',
    'isActive': true,
  },
  {
    'id': 'cuidador_idosos',
    'name': 'Cuidador de idosos',
    'mode': 'AGENDADO',
    'keywords': ['idosos', 'cuidador', 'companheiro', 'ajuda'],
    'iconKey': 'cuidador_idosos',
    'isActive': true,
  },
  {
    'id': 'apoio_domestico',
    'name': 'Empregada doméstica / apoio total',
    'mode': 'AGENDADO',
    'keywords': ['doméstica', 'apoio', 'casa', 'serviço doméstico'],
    'iconKey': 'apoio_domestico',
    'isActive': true,
  },
  {
    'id': 'daycare',
    'name': 'Creche / Daycare (informal)',
    'mode': 'AGENDADO',
    'keywords': ['creche', 'daycare', 'crianças', 'cuidar'],
    'iconKey': 'daycare',
    'isActive': true,
  },

  // PETS
  {
    'id': 'cuidador_cao',
    'name': 'Cuidador de cão / Pet sitter',
    'mode': 'AGENDADO',
    'keywords': ['cães', 'pets', 'cuidador', 'pet sitter'],
    'iconKey': 'cuidador_cao',
    'isActive': true,
  },
  {
    'id': 'dogwalker',
    'name': 'Dog walker',
    'mode': 'IMEDIATO',
    'keywords': ['dog walker', 'passear cão', 'caminhada'],
    'iconKey': 'dogwalker',
    'isActive': true,
  },
  {
    'id': 'banho_tosa',
    'name': 'Banho e tosa',
    'mode': 'AGENDADO',
    'keywords': ['banho', 'tosa', 'pets', 'cães'],
    'iconKey': 'banho_tosa',
    'isActive': true,
  },
  {
    'id': 'treinador_caes',
    'name': 'Treinador de cães',
    'mode': 'AGENDADO',
    'keywords': ['treinar cão', 'obediência', 'pets'],
    'iconKey': 'treinador_caes',
    'isActive': true,
  },

  // EDUCAÇÃO & AULAS
  {
    'id': 'explicador',
    'name': 'Explicador / Aulas particulares',
    'mode': 'AGENDADO',
    'keywords': ['explicador', 'aulas', 'estudo', 'reforço escolar'],
    'iconKey': 'explicador',
    'isActive': true,
  },
  {
    'id': 'aulas_matematica',
    'name': 'Aulas de Matemática',
    'mode': 'AGENDADO',
    'keywords': ['matemática', 'explicações', 'aulas', 'cálculo'],
    'iconKey': 'aulas_matematica',
    'isActive': true,
  },
  {
    'id': 'aulas_idiomas',
    'name': 'Aulas de idiomas',
    'mode': 'AGENDADO',
    'keywords': ['inglês', 'idiomas', 'línguas', 'aulas'],
    'iconKey': 'aulas_idiomas',
    'isActive': true,
  },
  {
    'id': 'aulas_musica',
    'name': 'Aulas de música',
    'mode': 'AGENDADO',
    'keywords': ['música', 'guitarra', 'piano', 'voz'],
    'iconKey': 'aulas_musica',
    'isActive': true,
  },
  {
    'id': 'explicacoes_universitarias',
    'name': 'Explicações universitárias',
    'mode': 'AGENDADO',
    'keywords': ['universidade', 'explicações', 'cadeiras', 'exames'],
    'iconKey': 'explicacoes_universitarias',
    'isActive': true,
  },

  // DIGITAL & CRIATIVO
  {
    'id': 'designer_grafico',
    'name': 'Designer gráfico',
    'mode': 'POR_PROPOSTA',
    'keywords': ['design', 'logo', 'flyer', 'cartaz'],
    'iconKey': 'designer_grafico',
    'isActive': true,
  },
  {
    'id': 'ilustrador',
    'name': 'Ilustrador / Artista digital',
    'mode': 'POR_PROPOSTA',
    'keywords': ['ilustração', 'desenho', 'retrato', 'arte digital'],
    'iconKey': 'ilustrador',
    'isActive': true,
  },
  {
    'id': 'fotografo',
    'name': 'Fotógrafo',
    'mode': 'POR_PROPOSTA',
    'keywords': ['fotografia', 'sessão', 'casamento', 'evento'],
    'iconKey': 'fotografo',
    'isActive': true,
  },
  {
    'id': 'videomaker',
    'name': 'Videomaker',
    'mode': 'POR_PROPOSTA',
    'keywords': ['vídeo', 'filmagem', 'edição', 'evento'],
    'iconKey': 'videomaker',
    'isActive': true,
  },
  {
    'id': 'editor_video',
    'name': 'Editor de vídeo',
    'mode': 'POR_PROPOSTA',
    'keywords': ['edição', 'vídeo', 'conteúdo', 'youtube'],
    'iconKey': 'editor_video',
    'isActive': true,
  },
  {
    'id': 'social_media',
    'name': 'Gestor de redes sociais',
    'mode': 'POR_PROPOSTA',
    'keywords': ['social media', 'instagram', 'facebook', 'marketing'],
    'iconKey': 'social_media',
    'isActive': true,
  },
  {
    'id': 'copywriter',
    'name': 'Copywriter / Redator',
    'mode': 'POR_PROPOSTA',
    'keywords': ['copywriting', 'redação', 'texto', 'conteúdo'],
    'iconKey': 'copywriter',
    'isActive': true,
  },
  {
    'id': 'web_designer',
    'name': 'Web designer',
    'mode': 'POR_PROPOSTA',
    'keywords': ['web design', 'website', 'landing page'],
    'iconKey': 'web_designer',
    'isActive': true,
  },
  {
    'id': 'programador',
    'name': 'Programador / Desenvolvedor',
    'mode': 'POR_PROPOSTA',
    'keywords': ['programador', 'app', 'website', 'software'],
    'iconKey': 'programador',
    'isActive': true,
  },
  {
    'id': 'seo_specialist',
    'name': 'Especialista em SEO',
    'mode': 'POR_PROPOSTA',
    'keywords': ['SEO', 'google', 'busca', 'otimização'],
    'iconKey': 'seo_specialist',
    'isActive': true,
  },
  {
    'id': 'ads_manager',
    'name': 'Gestor de anúncios (Google/Facebook Ads)',
    'mode': 'POR_PROPOSTA',
    'keywords': ['anúncios', 'ads', 'tráfego pago', 'google ads'],
    'iconKey': 'ads_manager',
    'isActive': true,
  },
  {
    'id': 'tradutor',
    'name': 'Tradutor / Intérprete',
    'mode': 'POR_PROPOSTA',
    'keywords': ['tradução', 'intérprete', 'idiomas'],
    'iconKey': 'tradutor',
    'isActive': true,
  },

  // NEGÓCIOS & CONSULTORIA
  {
    'id': 'consultor_negocios',
    'name': 'Consultor de negócios',
    'mode': 'POR_PROPOSTA',
    'keywords': ['consultoria', 'negócios', 'empresa', 'estratégia'],
    'iconKey': 'consultor_negocios',
    'isActive': true,
  },
  {
    'id': 'consultor_financeiro',
    'name': 'Consultor financeiro',
    'mode': 'POR_PROPOSTA',
    'keywords': ['finanças', 'consultoria', 'investimento', 'planeamento'],
    'iconKey': 'consultor_financeiro',
    'isActive': true,
  },
  {
    'id': 'contabilista',
    'name': 'Contabilista / Accountant',
    'mode': 'POR_PROPOSTA',
    'keywords': ['contabilidade', 'impostos', 'declarações'],
    'iconKey': 'contabilista',
    'isActive': true,
  },
  {
    'id': 'assistente_virtual',
    'name': 'Assistente virtual',
    'mode': 'AGENDADO',
    'keywords': ['assistente virtual', 'tarefas', 'administração'],
    'iconKey': 'assistente_virtual',
    'isActive': true,
  },
  {
    'id': 'recrutamento',
    'name': 'Recrutamento / RH',
    'mode': 'POR_PROPOSTA',
    'keywords': ['recrutamento', 'RH', 'emprego', 'entrevistas'],
    'iconKey': 'recrutamento',
    'isActive': true,
  },
  {
    'id': 'consultor_imobiliario',
    'name': 'Consultor imobiliário',
    'mode': 'AGENDADO',
    'keywords': ['imobiliário', 'casas', 'aluguer', 'comprar'],
    'iconKey': 'consultor_imobiliario',
    'isActive': true,
  },
  {
    'id': 'consultor_migracao',
    'name': 'Consultor de migração / vistos',
    'mode': 'AGENDADO',
    'keywords': ['vistos', 'migração', 'documentos', 'legal'],
    'iconKey': 'consultor_migracao',
    'isActive': true,
  },

  // EVENTOS & FESTAS
  {
    'id': 'confeitaria',
    'name': 'Confeitaria / Bolos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['bolo', 'doces', 'cake', 'aniversário', 'casamento'],
    'iconKey': 'confeitaria',
    'isActive': true,
  },
  {
    'id': 'catering',
    'name': 'Catering / Comida para eventos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['catering', 'buffet', 'evento', 'comida'],
    'iconKey': 'catering',
    'isActive': true,
  },
  {
    'id': 'decorador_eventos',
    'name': 'Decorador de eventos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['decoração', 'eventos', 'casamento', 'festa'],
    'iconKey': 'decorador_eventos',
    'isActive': true,
  },
  {
    'id': 'dj',
    'name': 'DJ / Música para eventos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['dj', 'música', 'evento', 'festa'],
    'iconKey': 'dj',
    'isActive': true,
  },
  {
    'id': 'animador_festas',
    'name': 'Animador de festas',
    'mode': 'AGENDADO',
    'keywords': ['animador', 'festas', 'crianças', 'animação'],
    'iconKey': 'animador_festas',
    'isActive': true,
  },
  {
    'id': 'planeador_casamentos',
    'name': 'Wedding planner / Planeador de casamentos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['casamento', 'wedding planner', 'evento'],
    'iconKey': 'planeador_casamentos',
    'isActive': true,
  },
  {
    'id': 'planeador_eventos',
    'name': 'Planeador de eventos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['eventos', 'planeamento', 'festas', 'corporativo'],
    'iconKey': 'planeador_eventos',
    'isActive': true,
  },

  // OUTROS / GERAIS
  {
    'id': 'consultor_tecnologia',
    'name': 'Consultor de tecnologia / IT',
    'mode': 'POR_PROPOSTA',
    'keywords': ['IT', 'tecnologia', 'sistemas', 'infraestrutura'],
    'iconKey': 'consultor_tecnologia',
    'isActive': true,
  },
  {
    'id': 'suporte_informatica',
    'name': 'Suporte de informática / Reparação PC',
    'mode': 'AGENDADO',
    'keywords': ['computador', 'suporte', 'reparação', 'PC'],
    'iconKey': 'suporte_informatica',
    'isActive': true,
  },
  {
    'id': 'seguranca_eventos',
    'name': 'Segurança para eventos',
    'mode': 'AGENDADO',
    'keywords': ['segurança', 'evento', 'vigilante'],
    'iconKey': 'seguranca_eventos',
    'isActive': true,
  },
  {
    'id': 'costureira',
    'name': 'Costureira / Ajustes de roupa',
    'mode': 'AGENDADO',
    'keywords': ['costura', 'ajustes', 'roupa', 'baínha'],
    'iconKey': 'costureira',
    'isActive': true,
  },
  {
    'id': 'reparacao_calcado',
    'name': 'Reparação de calçado',
    'mode': 'AGENDADO',
    'keywords': ['sapatos', 'reparação', 'calçado'],
    'iconKey': 'reparacao_calcado',
    'isActive': true,
  },
  // ==========================
  // CONSTRUCAO & REPARACOES (EXTRAS)
  // ==========================
  {
    'id': 'chaveiro',
    'name': 'Chaveiro',
    'mode': 'IMEDIATO',
    'keywords': ['chaveiro', 'chave', 'fechadura', 'locksmith', 'porta'],
    'iconKey': 'chaveiro',
    'isActive': true,
  },
  {
    'id': 'desentupimento',
    'name': 'Desentupimento',
    'mode': 'IMEDIATO',
    'keywords': ['desentupimento', 'entupido', 'esgoto', 'sanita', 'pia', 'drain'],
    'iconKey': 'plumber',
    'isActive': true,
  },
  {
    'id': 'instalacao_gas',
    'name': 'Instalação de gás',
    'mode': 'AGENDADO',
    'keywords': ['gás', 'instalação', 'esquentador', 'fogão', 'tubagem', 'gas'],
    'iconKey': 'instalacao_gas',
    'isActive': true,
  },
  {
    'id': 'aquecimento_caldeiras',
    'name': 'Aquecimento / Caldeiras',
    'mode': 'AGENDADO',
    'keywords': ['caldeira', 'aquecimento', 'radiador', 'termoacumulador', 'boiler'],
    'iconKey': 'aquecimento_caldeiras',
    'isActive': true,
  },
  {
    'id': 'reparacao_eletrodomesticos',
    'name': 'Reparação de eletrodomésticos',
    'mode': 'AGENDADO',
    'keywords': [
      'eletrodomésticos',
      'máquina de lavar',
      'frigorífico',
      'forno',
      'micro-ondas',
    ],
    'iconKey': 'reparacao_eletrodomesticos',
    'isActive': true,
  },
  {
    'id': 'reparacao_portoes',
    'name': 'Reparação de portões',
    'mode': 'AGENDADO',
    'keywords': ['portão', 'garagem', 'automatismo', 'motor', 'mola'],
    'iconKey': 'reparacao_portoes',
    'isActive': true,
  },
  {
    'id': 'gesso_drywall',
    'name': 'Gesso / Drywall',
    'mode': 'POR_PROPOSTA',
    'keywords': ['gesso', 'drywall', 'pladur', 'tetos falsos', 'revestimento'],
    'iconKey': 'gesso_drywall',
    'isActive': true,
  },
  {
    'id': 'telhados_coberturas',
    'name': 'Telhados e coberturas',
    'mode': 'POR_PROPOSTA',
    'keywords': ['telhado', 'cobertura', 'telhas', 'infiltração', 'calhas'],
    'iconKey': 'telhados_coberturas',
    'isActive': true,
  },
  {
    'id': 'impermeabilizacao',
    'name': 'Impermeabilização',
    'mode': 'POR_PROPOSTA',
    'keywords': ['impermeabilização', 'infiltração', 'humidade', 'isolamento'],
    'iconKey': 'impermeabilizacao',
    'isActive': true,
  },
  {
    'id': 'isolamento_termico',
    'name': 'Isolamento térmico/acústico',
    'mode': 'POR_PROPOSTA',
    'keywords': ['isolamento', 'térmico', 'acústico', 'paredes', 'teto'],
    'iconKey': 'isolamento_termico',
    'isActive': true,
  },
  {
    'id': 'ladrilhador',
    'name': 'Ladrilhador / Azulejista',
    'mode': 'POR_PROPOSTA',
    'keywords': ['ladrilho', 'azulejo', 'revestimento', 'piso', 'cerâmica'],
    'iconKey': 'ladrilhador',
    'isActive': true,
  },
  {
    'id': 'pavimentacao',
    'name': 'Pavimentação',
    'mode': 'POR_PROPOSTA',
    'keywords': ['pavimentação', 'calçada', 'asfalto', 'pavimento', 'bloquete'],
    'iconKey': 'pavimentacao',
    'isActive': true,
  },
  {
    'id': 'marcenaria',
    'name': 'Marcenaria',
    'mode': 'POR_PROPOSTA',
    'keywords': ['marcenaria', 'madeira', 'móveis sob medida', 'armário'],
    'iconKey': 'marcenaria',
    'isActive': true,
  },
  {
    'id': 'montagem_cozinhas',
    'name': 'Montagem de cozinhas',
    'mode': 'POR_PROPOSTA',
    'keywords': ['cozinha', 'armários', 'bancada', 'montagem', 'móveis'],
    'iconKey': 'montagem_cozinhas',
    'isActive': true,
  },
  {
    'id': 'seguranca_eletronica',
    'name': 'Segurança eletrónica / CCTV',
    'mode': 'AGENDADO',
    'keywords': ['cctv', 'câmeras', 'alarme', 'segurança', 'videoporteiro'],
    'iconKey': 'seguranca_eletronica',
    'isActive': true,
  },

  // LIMPEZA & ORGANIZACAO (EXTRAS)
  {
    'id': 'limpeza_estofados',
    'name': 'Limpeza de estofados',
    'mode': 'AGENDADO',
    'keywords': ['estofados', 'sofá', 'cadeira', 'higienização', 'limpeza'],
    'iconKey': 'cleaning',
    'isActive': true,
  },
  {
    'id': 'limpeza_tapetes',
    'name': 'Limpeza de tapetes',
    'mode': 'AGENDADO',
    'keywords': ['tapetes', 'carpete', 'higienização', 'limpeza profunda'],
    'iconKey': 'cleaning',
    'isActive': true,
  },
  {
    'id': 'limpeza_fachadas',
    'name': 'Limpeza de fachadas',
    'mode': 'AGENDADO',
    'keywords': ['fachada', 'altura', 'vidros', 'prédio'],
    'iconKey': 'cleaning',
    'isActive': true,
  },
  {
    'id': 'limpeza_pos_evento',
    'name': 'Limpeza pós-evento',
    'mode': 'AGENDADO',
    'keywords': ['evento', 'festa', 'limpeza', 'pós-evento'],
    'iconKey': 'cleaning',
    'isActive': true,
  },
  {
    'id': 'dedetizacao',
    'name': 'Dedetização / Controle de pragas',
    'mode': 'AGENDADO',
    'keywords': ['dedetização', 'pragas', 'insetos', 'ratos', 'baratas'],
    'iconKey': 'cleaning',
    'isActive': true,
  },
  {
    'id': 'desinfeccao',
    'name': 'Desinfeção',
    'mode': 'AGENDADO',
    'keywords': ['desinfeção', 'higienização', 'vírus', 'bactérias'],
    'iconKey': 'cleaning',
    'isActive': true,
  },
  {
    'id': 'lavagem_pressao',
    'name': 'Lavagem a pressão',
    'mode': 'AGENDADO',
    'keywords': ['lavagem', 'pressão', 'jato', 'pavimento', 'fachada'],
    'iconKey': 'cleaning',
    'isActive': true,
  },
  {
    'id': 'remocao_entulho',
    'name': 'Remoção de entulho',
    'mode': 'AGENDADO',
    'keywords': ['entulho', 'remoção', 'obra', 'descarga', 'caçamba'],
    'iconKey': 'cleaning',
    'isActive': true,
  },
  {
    'id': 'limpeza_chamines',
    'name': 'Limpeza de chaminés',
    'mode': 'AGENDADO',
    'keywords': ['chaminé', 'limpeza', 'fumos', 'lareira'],
    'iconKey': 'cleaning',
    'isActive': true,
  },

  // MUDANCAS & LOGISTICA
  {
    'id': 'mudancas',
    'name': 'Mudanças',
    'mode': 'AGENDADO',
    'keywords': ['mudanças', 'mudanca', 'transporte', 'casa', 'escritório'],
    'iconKey': 'move',
    'isActive': true,
  },
  {
    'id': 'fretes',
    'name': 'Fretes',
    'mode': 'IMEDIATO',
    'keywords': ['frete', 'transporte', 'carga', 'entrega', 'camião'],
    'iconKey': 'move',
    'isActive': true,
  },
  {
    'id': 'embalagem_mudancas',
    'name': 'Embalagem para mudanças',
    'mode': 'AGENDADO',
    'keywords': ['embalagem', 'mudança', 'caixas', 'proteção'],
    'iconKey': 'move',
    'isActive': true,
  },
  {
    'id': 'armazenamento',
    'name': 'Armazenamento / Self-storage',
    'mode': 'AGENDADO',
    'keywords': ['armazenamento', 'self storage', 'armazém', 'depósito'],
    'iconKey': 'move',
    'isActive': true,
  },

  // AUTO & TRANSPORTE (EXTRAS)
  {
    'id': 'borracheiro',
    'name': 'Borracheiro',
    'mode': 'IMEDIATO',
    'keywords': ['borracheiro', 'pneu', 'furo', 'reparo'],
    'iconKey': 'borracheiro',
    'isActive': true,
  },
  {
    'id': 'troca_oleo',
    'name': 'Troca de óleo',
    'mode': 'IMEDIATO',
    'keywords': ['óleo', 'troca', 'motor', 'lubrificação'],
    'iconKey': 'troca_oleo',
    'isActive': true,
  },
  {
    'id': 'alinhamento_balanceamento',
    'name': 'Alinhamento e balanceamento',
    'mode': 'AGENDADO',
    'keywords': ['alinhamento', 'balanceamento', 'pneus', 'suspensão'],
    'iconKey': 'alinhamento_balanceamento',
    'isActive': true,
  },
  {
    'id': 'inspecao_veicular',
    'name': 'Inspeção veicular',
    'mode': 'AGENDADO',
    'keywords': ['inspeção', 'vistoria', 'veículo', 'documentos'],
    'iconKey': 'inspecao_veicular',
    'isActive': true,
  },
  {
    'id': 'funilaria',
    'name': 'Funilaria',
    'mode': 'POR_PROPOSTA',
    'keywords': ['funilaria', 'lataria', 'amassado', 'carroceria'],
    'iconKey': 'funilaria',
    'isActive': true,
  },
  {
    'id': 'pintura_auto',
    'name': 'Pintura automóvel',
    'mode': 'POR_PROPOSTA',
    'keywords': ['pintura', 'automóvel', 'carro', 'retoque'],
    'iconKey': 'pintura_auto',
    'isActive': true,
  },
  {
    'id': 'mecanico_moto',
    'name': 'Mecânico de motos',
    'mode': 'IMEDIATO',
    'keywords': ['moto', 'mecânico', 'motocicleta', 'avaria'],
    'iconKey': 'mecanico',
    'isActive': true,
  },

  // SAUDE & CUIDADOS
  {
    'id': 'fisioterapia',
    'name': 'Fisioterapia',
    'mode': 'AGENDADO',
    'keywords': ['fisioterapia', 'reabilitação', 'dor', 'movimento'],
    'iconKey': 'fisioterapia',
    'isActive': true,
  },
  {
    'id': 'psicologo',
    'name': 'Psicólogo',
    'mode': 'AGENDADO',
    'keywords': ['psicólogo', 'terapia', 'saúde mental', 'consulta'],
    'iconKey': 'psicologo',
    'isActive': true,
  },
  {
    'id': 'terapia_ocupacional',
    'name': 'Terapia ocupacional',
    'mode': 'AGENDADO',
    'keywords': ['terapia ocupacional', 'reabilitação', 'autonomia'],
    'iconKey': 'terapia_ocupacional',
    'isActive': true,
  },
  {
    'id': 'enfermagem_domiciliar',
    'name': 'Enfermagem domiciliária',
    'mode': 'AGENDADO',
    'keywords': ['enfermagem', 'domicílio', 'cuidados', 'injeção'],
    'iconKey': 'enfermagem_domiciliar',
    'isActive': true,
  },
  {
    'id': 'cuidados_pos_operatorio',
    'name': 'Cuidados pós-operatório',
    'mode': 'AGENDADO',
    'keywords': ['pós-operatório', 'curativos', 'recuperação'],
    'iconKey': 'cuidados_pos_operatorio',
    'isActive': true,
  },
  {
    'id': 'fonoaudiologia',
    'name': 'Fonoaudiologia',
    'mode': 'AGENDADO',
    'keywords': ['fonoaudiologia', 'fala', 'voz', 'audição'],
    'iconKey': 'fonoaudiologia',
    'isActive': true,
  },

  // BELEZA & BEM-ESTAR (EXTRAS)
  {
    'id': 'barbeiro',
    'name': 'Barbeiro',
    'mode': 'AGENDADO',
    'keywords': ['barbeiro', 'barba', 'corte masculino', 'barbearia'],
    'iconKey': 'cabeleireiro',
    'isActive': true,
  },
  {
    'id': 'depilacao',
    'name': 'Depilação',
    'mode': 'AGENDADO',
    'keywords': ['depilação', 'cera', 'laser', 'pelos'],
    'iconKey': 'depilacao',
    'isActive': true,
  },
  {
    'id': 'sobrancelhas',
    'name': 'Design de sobrancelhas',
    'mode': 'AGENDADO',
    'keywords': ['sobrancelhas', 'design', 'henna'],
    'iconKey': 'sobrancelhas',
    'isActive': true,
  },
  {
    'id': 'tatuador',
    'name': 'Tatuador',
    'mode': 'AGENDADO',
    'keywords': ['tatuagem', 'tattoo', 'tatuador'],
    'iconKey': 'tatuador',
    'isActive': true,
  },
  {
    'id': 'piercing',
    'name': 'Piercing',
    'mode': 'AGENDADO',
    'keywords': ['piercing', 'furo', 'joia'],
    'iconKey': 'piercing',
    'isActive': true,
  },
  {
    'id': 'trancista',
    'name': 'Trancista',
    'mode': 'AGENDADO',
    'keywords': ['tranças', 'trancista', 'cabelo'],
    'iconKey': 'trancista',
    'isActive': true,
  },
  {
    'id': 'bronzeamento',
    'name': 'Bronzeamento',
    'mode': 'AGENDADO',
    'keywords': ['bronzeamento', 'sol', 'spray tan'],
    'iconKey': 'bronzeamento',
    'isActive': true,
  },

  // PETS (EXTRAS)
  {
    'id': 'veterinario',
    'name': 'Veterinário',
    'mode': 'AGENDADO',
    'keywords': ['veterinário', 'animais', 'consulta', 'vacina'],
    'iconKey': 'pet',
    'isActive': true,
  },
  {
    'id': 'hotel_pet',
    'name': 'Hotel / Creche pet',
    'mode': 'AGENDADO',
    'keywords': ['hotel', 'creche', 'pet', 'cão', 'gato'],
    'iconKey': 'pet',
    'isActive': true,
  },

  // EDUCACAO & AULAS (EXTRAS)
  {
    'id': 'aulas_informatica',
    'name': 'Aulas de informática',
    'mode': 'AGENDADO',
    'keywords': ['informática', 'computador', 'excel', 'aulas'],
    'iconKey': 'aulas_informatica',
    'isActive': true,
  },
  {
    'id': 'aulas_danca',
    'name': 'Aulas de dança',
    'mode': 'AGENDADO',
    'keywords': ['dança', 'aulas', 'ballet', 'kizomba'],
    'iconKey': 'aulas_danca',
    'isActive': true,
  },
  {
    'id': 'aulas_conducao',
    'name': 'Aulas de condução',
    'mode': 'AGENDADO',
    'keywords': ['condução', 'carta', 'autoescola'],
    'iconKey': 'aulas_conducao',
    'isActive': true,
  },
  {
    'id': 'aulas_artes',
    'name': 'Aulas de artes',
    'mode': 'AGENDADO',
    'keywords': ['artes', 'desenho', 'pintura', 'criatividade'],
    'iconKey': 'aulas_artes',
    'isActive': true,
  },
  {
    'id': 'aulas_culinaria',
    'name': 'Aulas de culinária',
    'mode': 'AGENDADO',
    'keywords': ['culinária', 'cozinha', 'aulas', 'receitas'],
    'iconKey': 'aulas_culinaria',
    'isActive': true,
  },

  // TECNOLOGIA & DIGITAL (EXTRAS)
  {
    'id': 'reparacao_telemovel',
    'name': 'Reparação de telemóveis',
    'mode': 'AGENDADO',
    'keywords': ['telemóvel', 'smartphone', 'reparação', 'ecrã', 'bateria'],
    'iconKey': 'reparacao_telemovel',
    'isActive': true,
  },
  {
    'id': 'reparacao_tablet',
    'name': 'Reparação de tablets',
    'mode': 'AGENDADO',
    'keywords': ['tablet', 'reparação', 'ecrã', 'bateria'],
    'iconKey': 'reparacao_tablet',
    'isActive': true,
  },
  {
    'id': 'reparacao_console',
    'name': 'Reparação de consolas',
    'mode': 'AGENDADO',
    'keywords': ['consola', 'playstation', 'xbox', 'nintendo'],
    'iconKey': 'reparacao_console',
    'isActive': true,
  },
  {
    'id': 'tecnico_impressora',
    'name': 'Técnico de impressoras',
    'mode': 'AGENDADO',
    'keywords': ['impressora', 'tinta', 'scanner', 'reparação'],
    'iconKey': 'tecnico_impressora',
    'isActive': true,
  },
  {
    'id': 'suporte_redes',
    'name': 'Suporte de redes',
    'mode': 'AGENDADO',
    'keywords': ['redes', 'wifi', 'router', 'internet', 'cablagem'],
    'iconKey': 'suporte_redes',
    'isActive': true,
  },
  {
    'id': 'ciberseguranca',
    'name': 'Cibersegurança',
    'mode': 'POR_PROPOSTA',
    'keywords': ['cibersegurança', 'segurança', 'dados', 'proteção'],
    'iconKey': 'ciberseguranca',
    'isActive': true,
  },
  {
    'id': 'ux_ui',
    'name': 'UX/UI Designer',
    'mode': 'POR_PROPOSTA',
    'keywords': ['ux', 'ui', 'design', 'produto digital'],
    'iconKey': 'ux_ui',
    'isActive': true,
  },
  {
    'id': 'marketing_digital',
    'name': 'Marketing digital',
    'mode': 'POR_PROPOSTA',
    'keywords': ['marketing digital', 'seo', 'ads', 'redes sociais'],
    'iconKey': 'marketing_digital',
    'isActive': true,
  },
  {
    'id': 'gestor_ecommerce',
    'name': 'Gestor de e-commerce',
    'mode': 'POR_PROPOSTA',
    'keywords': ['e-commerce', 'loja online', 'vendas', 'marketplace'],
    'iconKey': 'gestor_ecommerce',
    'isActive': true,
  },
  {
    'id': 'analista_dados',
    'name': 'Analista de dados',
    'mode': 'POR_PROPOSTA',
    'keywords': ['dados', 'analise', 'bi', 'relatórios'],
    'iconKey': 'analista_dados',
    'isActive': true,
  },

  // NEGOCIOS & LEGAL (EXTRAS)
  {
    'id': 'advogado',
    'name': 'Advogado / Consultoria jurídica',
    'mode': 'POR_PROPOSTA',
    'keywords': ['advogado', 'jurídico', 'legal', 'contratos'],
    'iconKey': 'advogado',
    'isActive': true,
  },
  {
    'id': 'notario',
    'name': 'Notário',
    'mode': 'AGENDADO',
    'keywords': ['notário', 'cartório', 'documentos', 'certidão'],
    'iconKey': 'notario',
    'isActive': true,
  },
  {
    'id': 'despachante',
    'name': 'Despachante',
    'mode': 'AGENDADO',
    'keywords': ['despachante', 'documentos', 'legalização'],
    'iconKey': 'despachante',
    'isActive': true,
  },
  {
    'id': 'gestor_projetos',
    'name': 'Gestor de projetos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['gestão de projetos', 'project manager', 'planeamento'],
    'iconKey': 'gestor_projetos',
    'isActive': true,
  },
  {
    'id': 'auditoria',
    'name': 'Auditoria',
    'mode': 'POR_PROPOSTA',
    'keywords': ['auditoria', 'compliance', 'processos', 'risco'],
    'iconKey': 'auditoria',
    'isActive': true,
  },
  {
    'id': 'consultor_marketing',
    'name': 'Consultor de marketing',
    'mode': 'POR_PROPOSTA',
    'keywords': ['consultoria', 'marketing', 'estratégia', 'branding'],
    'iconKey': 'consultor_marketing',
    'isActive': true,
  },

  // EVENTOS & FESTAS (EXTRAS)
  {
    'id': 'florista',
    'name': 'Florista',
    'mode': 'POR_PROPOSTA',
    'keywords': ['flores', 'arranjos', 'bouquet', 'eventos'],
    'iconKey': 'florista',
    'isActive': true,
  },
  {
    'id': 'bartender',
    'name': 'Bartender / Barman',
    'mode': 'AGENDADO',
    'keywords': ['bartender', 'barman', 'cocktails', 'bar'],
    'iconKey': 'bartender',
    'isActive': true,
  },
  {
    'id': 'banda_musical',
    'name': 'Banda / Música ao vivo',
    'mode': 'POR_PROPOSTA',
    'keywords': ['banda', 'música ao vivo', 'show', 'evento'],
    'iconKey': 'banda_musical',
    'isActive': true,
  },
  {
    'id': 'som_iluminacao',
    'name': 'Som e iluminação',
    'mode': 'POR_PROPOSTA',
    'keywords': ['som', 'iluminação', 'palco', 'evento'],
    'iconKey': 'som_iluminacao',
    'isActive': true,
  },
  {
    'id': 'aluguer_equipamentos_evento',
    'name': 'Aluguer de equipamentos',
    'mode': 'POR_PROPOSTA',
    'keywords': ['aluguer', 'equipamentos', 'evento', 'palco'],
    'iconKey': 'aluguer_equipamentos_evento',
    'isActive': true,
  },
  {
    'id': 'aluguer_tendas',
    'name': 'Aluguer de tendas',
    'mode': 'POR_PROPOSTA',
    'keywords': ['tendas', 'aluguer', 'evento', 'cobertura'],
    'iconKey': 'aluguer_tendas',
    'isActive': true,
  },

  // COZINHA & ALIMENTACAO (EXTRAS)
  {
    'id': 'cozinheiro_domicilio',
    'name': 'Cozinheiro ao domicílio',
    'mode': 'AGENDADO',
    'keywords': ['cozinheiro', 'domicílio', 'refeições', 'casa'],
    'iconKey': 'cozinheiro_domicilio',
    'isActive': true,
  },
  {
    'id': 'chef_privado',
    'name': 'Chef privado',
    'mode': 'AGENDADO',
    'keywords': ['chef', 'privado', 'jantar', 'experiência'],
    'iconKey': 'chef_privado',
    'isActive': true,
  },
  {
    'id': 'marmitas_caseiras',
    'name': 'Marmitas caseiras',
    'mode': 'AGENDADO',
    'keywords': ['marmitas', 'meal prep', 'comida', 'saudável'],
    'iconKey': 'marmitas_caseiras',
    'isActive': true,
  },
];
