import 'package:chegaja_v2/core/catalog/service_intent.dart';
import 'package:chegaja_v2/core/catalog/service_taxonomy.dart';
import 'package:chegaja_v2/core/catalog/service_taxonomy_normalizer.dart';
import 'package:chegaja_v2/core/models/category_approval_types.dart';
import 'package:chegaja_v2/core/models/servico.dart';

class ServiceTaxonomyCatalog {
  const ServiceTaxonomyCatalog._();

  static const categories = <ServiceTaxonomyCategory>[
    ServiceTaxonomyCategory(
      id: 'home_repairs',
      label: 'Casa e reparacoes',
      description: 'Reparacoes, instalacoes e manutencao dentro de casa.',
      iconKey: 'home_repairs',
      sortOrder: 10,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'plumbing',
          parentCategoryId: 'home_repairs',
          label: 'Canalizacao',
          description: 'Fugas, torneiras, canos, sanitas e pequenos arranjos.',
          aliases: [
            'canalizador',
            'cano',
            'tubo',
            'fuga de agua',
            'torneira',
            'chuveiro',
            'sanita',
            'autoclismo',
            'pia',
            'lava louca',
          ],
          commonPhrases: [
            'cano rebentou',
            'agua a pingar',
            'montar chuveiro',
            'torneira estragada',
            'sanita nao descarrega',
          ],
          examples: [
            'tenho agua a sair do tubo',
            'preciso montar chuveiro',
            'canalizador para pia',
          ],
          allowedIntents: [
            ServiceIntent.now,
            ServiceIntent.scheduled,
            ServiceIntent.quote,
          ],
          defaultIntent: ServiceIntent.now,
          legacyServicoIds: ['canalizador'],
          legacyNames: [
            'Canalizador',
            'Reparacao de torneiras',
            'Instalacao de chuveiros',
            'Substituicao de sanitas',
          ],
          sortOrder: 10,
        ),
        ServiceTaxonomySubcategory(
          id: 'electricity',
          parentCategoryId: 'home_repairs',
          label: 'Eletricidade',
          description: 'Luz, tomadas, quadro eletrico e avarias eletricas.',
          aliases: [
            'eletricista',
            'luz',
            'tomada',
            'quadro',
            'quadro eletrico',
            'disjuntor',
            'lampada',
            'curto circuito',
          ],
          commonPhrases: [
            'arranjar luz',
            'tomada nao funciona',
            'quadro disparou',
            'energia caiu',
          ],
          examples: [
            'preciso de eletricista',
            'a luz foi abaixo',
          ],
          allowedIntents: [
            ServiceIntent.now,
            ServiceIntent.scheduled,
            ServiceIntent.quote,
          ],
          defaultIntent: ServiceIntent.now,
          legacyServicoIds: ['eletricista'],
          legacyNames: [
            'Eletricista',
            'Diagnostico de iluminacao',
            'Reparacao de tomadas',
          ],
          sensitiveRequirementId: 'electricity',
          riskLevel: CategoryRiskLevel.sensitive,
          requiresApproval: true,
          sortOrder: 20,
        ),
        ServiceTaxonomySubcategory(
          id: 'gas',
          parentCategoryId: 'home_repairs',
          label: 'Gas',
          description: 'Servicos ligados a gas e esquentadores.',
          aliases: ['gas', 'esquentador', 'fuga de gas', 'canalizacao de gas'],
          commonPhrases: ['cheiro a gas', 'esquentador nao liga'],
          examples: ['preciso ver fuga de gas'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: [],
          legacyNames: ['Gas', 'Esquentador'],
          sensitiveRequirementId: 'gas',
          riskLevel: CategoryRiskLevel.sensitive,
          requiresApproval: true,
          sortOrder: 30,
        ),
        ServiceTaxonomySubcategory(
          id: 'general_repairs',
          parentCategoryId: 'home_repairs',
          label: 'Reparacoes gerais',
          description: 'Pequenos arranjos e manutencao domestica.',
          aliases: ['faz tudo', 'arranjos', 'reparacoes domesticas'],
          commonPhrases: ['pequenos arranjos', 'ajuda em casa'],
          examples: ['preciso de alguem para arranjar coisas em casa'],
          allowedIntents: [
            ServiceIntent.now,
            ServiceIntent.scheduled,
            ServiceIntent.quote,
          ],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: ['serralheiro'],
          legacyNames: ['Servicos de reparacao', 'Serralheiro'],
          sortOrder: 40,
        ),
        ServiceTaxonomySubcategory(
          id: 'painting',
          parentCategoryId: 'home_repairs',
          label: 'Pintura',
          description: 'Pintura interior, exterior e retoques.',
          aliases: ['pintor', 'parede', 'tinta', 'pintar casa'],
          commonPhrases: ['pintar quarto', 'pintura de casa'],
          examples: ['preciso pintar a sala'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: ['pintor'],
          legacyNames: ['Pintor'],
          sortOrder: 50,
        ),
        ServiceTaxonomySubcategory(
          id: 'carpentry',
          parentCategoryId: 'home_repairs',
          label: 'Carpintaria',
          description: 'Madeira, portas, armarios e moveis por medida.',
          aliases: ['carpinteiro', 'madeira', 'portas', 'armarios'],
          commonPhrases: ['moveis por medida', 'arranjar porta'],
          examples: ['preciso de armario por medida'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: ['carpinteiro'],
          legacyNames: ['Carpinteiro'],
          sortOrder: 60,
        ),
        ServiceTaxonomySubcategory(
          id: 'furniture_assembly',
          parentCategoryId: 'home_repairs',
          label: 'Montagem de moveis',
          description: 'Montagem de camas, mesas, armarios e prateleiras.',
          aliases: ['montagem', 'moveis', 'armario', 'ikea'],
          commonPhrases: ['montar armario', 'montar cama', 'montar movel'],
          examples: ['homem para montar armario'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: ['montagem_moveis'],
          legacyNames: ['Montagem de moveis'],
          sortOrder: 70,
        ),
        ServiceTaxonomySubcategory(
          id: 'air_conditioning',
          parentCategoryId: 'home_repairs',
          label: 'Ar condicionado',
          description: 'Instalacao e manutencao de climatizacao.',
          aliases: ['ar condicionado', 'ac', 'climatizacao'],
          commonPhrases: ['instalar ac', 'manutencao ar condicionado'],
          examples: ['o ar condicionado nao arrefece'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Ar condicionado'],
          sortOrder: 80,
        ),
      ],
    ),
    ServiceTaxonomyCategory(
      id: 'cleaning_maintenance',
      label: 'Limpeza e manutencao',
      description: 'Limpezas, lavandaria, jardim e manutencao de espacos.',
      iconKey: 'cleaning',
      sortOrder: 20,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'home_cleaning',
          parentCategoryId: 'cleaning_maintenance',
          label: 'Limpeza domestica',
          description: 'Limpeza regular ou pontual de casas.',
          aliases: ['limpeza', 'limpar casa', 'faxina', 'domestica'],
          commonPhrases: ['senhora limpar casa', 'senhora da limpeza'],
          examples: ['preciso de limpeza semanal'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Limpeza profissional', 'Limpeza domestica'],
          sortOrder: 10,
        ),
        ServiceTaxonomySubcategory(
          id: 'deep_cleaning',
          parentCategoryId: 'cleaning_maintenance',
          label: 'Limpeza profunda e pos-obra',
          description: 'Limpeza pesada, pos-obra e higienizacao.',
          aliases: ['pos obra', 'limpeza profunda', 'higienizacao'],
          commonPhrases: ['limpeza de obra', 'poeira de obra'],
          examples: ['limpeza depois de obra'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Limpeza pos-obra', 'Limpeza profunda'],
          sortOrder: 20,
        ),
        ServiceTaxonomySubcategory(
          id: 'laundry',
          parentCategoryId: 'cleaning_maintenance',
          label: 'Lavandaria',
          description: 'Lavar, passar e engomar roupa.',
          aliases: ['lavandaria', 'roupa', 'engomar', 'passar roupa'],
          commonPhrases: ['lavar roupa', 'passar roupa'],
          examples: ['preciso de engomadoria'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Lavandaria'],
          sortOrder: 30,
        ),
        ServiceTaxonomySubcategory(
          id: 'gardening',
          parentCategoryId: 'cleaning_maintenance',
          label: 'Jardinagem',
          description: 'Jardim, relva, poda e manutencao exterior.',
          aliases: ['jardineiro', 'jardim', 'relva', 'podar'],
          commonPhrases: ['cortar relva', 'limpar jardim'],
          examples: ['preciso de jardineiro'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Jardinagem'],
          sortOrder: 40,
        ),
        ServiceTaxonomySubcategory(
          id: 'maintenance_spaces',
          parentCategoryId: 'cleaning_maintenance',
          label: 'Manutencao de espacos',
          description: 'Condominio, piscinas, garagem e espacos comuns.',
          aliases: ['condominio', 'piscina', 'garagem', 'manutencao'],
          commonPhrases: ['manutencao piscina', 'limpeza condominio'],
          examples: ['manutencao de espaco comum'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Manutencao de espacos'],
          sortOrder: 50,
        ),
      ],
    ),
    ServiceTaxonomyCategory(
      id: 'beauty_wellbeing',
      label: 'Beleza e bem-estar',
      description: 'Cabelo, estetica, massagem, treino e bem-estar.',
      iconKey: 'beauty',
      sortOrder: 30,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'hair_barber',
          parentCategoryId: 'beauty_wellbeing',
          label: 'Cabelo e barbearia',
          description: 'Cortes, barba, penteados e tratamentos de cabelo.',
          aliases: ['cabeleireiro', 'barbeiro', 'corte', 'barba'],
          commonPhrases: ['cortar cabelo', 'fazer barba'],
          examples: ['barbeiro para degrade'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: ['barbeiro', 'cabeleireiro'],
          legacyNames: ['Barbeiro', 'Cabeleireiro'],
          sortOrder: 10,
        ),
        ServiceTaxonomySubcategory(
          id: 'makeup',
          parentCategoryId: 'beauty_wellbeing',
          label: 'Maquilhagem',
          description: 'Maquilhagem para eventos, noivas e sessoes.',
          aliases: ['maquilhagem', 'maquilhadora', 'make', 'noiva'],
          commonPhrases: ['maquilhagem para festa', 'make de noiva'],
          examples: ['maquilhadora para casamento'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Maquilhagem'],
          sortOrder: 20,
        ),
        ServiceTaxonomySubcategory(
          id: 'nails',
          parentCategoryId: 'beauty_wellbeing',
          label: 'Unhas',
          description: 'Manicure, pedicure, gel e nail design.',
          aliases: ['unhas', 'manicure', 'pedicure', 'gel'],
          commonPhrases: ['fazer unhas', 'unhas de gel'],
          examples: ['manicure ao domicilio'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Unhas'],
          sortOrder: 30,
        ),
        ServiceTaxonomySubcategory(
          id: 'massage',
          parentCategoryId: 'beauty_wellbeing',
          label: 'Massagem',
          description: 'Massagens de relaxamento e bem-estar.',
          aliases: ['massagem', 'massagista', 'relaxamento'],
          commonPhrases: ['massagem relaxante', 'massagem terapeutica'],
          examples: ['massagista em casa'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Massagem'],
          sortOrder: 40,
        ),
        ServiceTaxonomySubcategory(
          id: 'personal_training',
          parentCategoryId: 'beauty_wellbeing',
          label: 'Personal trainer',
          description: 'Treino acompanhado, fitness e objetivos fisicos.',
          aliases: ['pt', 'personal trainer', 'treino', 'fitness'],
          commonPhrases: ['ganhar massa', 'perder peso'],
          examples: ['personal trainer ao domicilio'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Personal trainer'],
          sensitiveRequirementId: 'training_nutrition',
          riskLevel: CategoryRiskLevel.sensitive,
          requiresApproval: true,
          sortOrder: 50,
        ),
        ServiceTaxonomySubcategory(
          id: 'nutrition',
          parentCategoryId: 'beauty_wellbeing',
          label: 'Nutricao',
          description: 'Planos alimentares e acompanhamento nutricional.',
          aliases: ['nutricionista', 'nutricao', 'dieta', 'plano alimentar'],
          commonPhrases: ['fazer dieta', 'plano de alimentacao'],
          examples: ['nutricionista online'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Nutricao'],
          sensitiveRequirementId: 'training_nutrition',
          riskLevel: CategoryRiskLevel.sensitive,
          requiresApproval: true,
          sortOrder: 60,
        ),
      ],
    ),
    ServiceTaxonomyCategory(
      id: 'food_catering',
      label: 'Alimentacao',
      description: 'Bolos, catering, marmitas e comida personalizada.',
      iconKey: 'food',
      sortOrder: 40,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'cakes_confectionery',
          parentCategoryId: 'food_catering',
          label: 'Bolos e confeitaria',
          description: 'Bolos, doces, sobremesas e cake design.',
          aliases: ['bolo', 'bolos', 'confeitaria', 'docinhos', 'sobremesa'],
          commonPhrases: ['bolo aniversario', 'bolo de aniversario'],
          examples: ['preciso de bolo para casamento'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: [
            'confeitaria',
            'cake_designer',
            'bolos_personalizados',
          ],
          legacyNames: [
            'Confeitaria',
            'Cake designer',
            'Bolos personalizados',
          ],
          sortOrder: 10,
        ),
        ServiceTaxonomySubcategory(
          id: 'catering',
          parentCategoryId: 'food_catering',
          label: 'Catering',
          description: 'Comida para eventos, festas e equipas.',
          aliases: ['catering', 'buffet', 'comida para evento'],
          commonPhrases: ['catering pequeno', 'comida para festa'],
          examples: ['buffet para aniversario'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Catering'],
          sensitiveRequirementId: 'professional_food',
          riskLevel: CategoryRiskLevel.sensitive,
          requiresApproval: true,
          sortOrder: 20,
        ),
        ServiceTaxonomySubcategory(
          id: 'meal_prep',
          parentCategoryId: 'food_catering',
          label: 'Marmitas semanais',
          description: 'Preparacao de refeicoes e comida da semana.',
          aliases: ['marmita', 'meal prep', 'comida da semana'],
          commonPhrases: ['marmitas semanais', 'almoco semanal'],
          examples: ['preciso de comida para a semana'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Marmitas semanais'],
          sortOrder: 30,
        ),
        ServiceTaxonomySubcategory(
          id: 'healthy_food',
          parentCategoryId: 'food_catering',
          label: 'Comida saudavel',
          description: 'Refeicoes leves, saudaveis e personalizadas.',
          aliases: ['comida saudavel', 'low carb', 'saladas'],
          commonPhrases: ['comida de dieta', 'comida equilibrada'],
          examples: ['quero comida saudavel para casa'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Comida saudavel'],
          sortOrder: 40,
        ),
        ServiceTaxonomySubcategory(
          id: 'athlete_meals',
          parentCategoryId: 'food_catering',
          label: 'Comida para atletas',
          description: 'Refeicoes orientadas a treino e objetivos fisicos.',
          aliases: ['comida fitness', 'comida de treino', 'proteina'],
          commonPhrases: ['comida fitness', 'marmita fitness'],
          examples: ['comida para ganhar massa'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Comida para atletas'],
          sensitiveRequirementId: 'training_nutrition',
          riskLevel: CategoryRiskLevel.sensitive,
          requiresApproval: true,
          sortOrder: 50,
        ),
      ],
    ),
    ServiceTaxonomyCategory(
      id: 'events',
      label: 'Eventos',
      description: 'Fotografia, video, decoracao e organizacao de eventos.',
      iconKey: 'events',
      sortOrder: 50,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'photography',
          parentCategoryId: 'events',
          label: 'Fotografia',
          description: 'Fotografos para eventos, retratos e sessoes.',
          aliases: ['fotografo', 'fotografia', 'fotos', 'sessao'],
          commonPhrases: ['sessao de fotos', 'fotos de casamento'],
          examples: ['fotografo para aniversario'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Fotografia', 'Sessao de retratos'],
          sortOrder: 10,
        ),
        ServiceTaxonomySubcategory(
          id: 'video',
          parentCategoryId: 'events',
          label: 'Video',
          description: 'Filmagem, edicao e producao de video.',
          aliases: ['video', 'videografo', 'filmagem', 'edicao de video'],
          commonPhrases: ['filmar evento', 'editar video'],
          examples: ['video para casamento'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Video'],
          sortOrder: 20,
        ),
        ServiceTaxonomySubcategory(
          id: 'decoration',
          parentCategoryId: 'events',
          label: 'Decoracao',
          description: 'Decoracao de festas, mesas e ambientes.',
          aliases: ['decoracao', 'decoradora', 'baloes', 'mesa posta'],
          commonPhrases: ['decoracao infantil', 'decorar festa'],
          examples: ['decoracao para aniversario'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Decoracao'],
          sortOrder: 30,
        ),
        ServiceTaxonomySubcategory(
          id: 'dj_sound',
          parentCategoryId: 'events',
          label: 'DJ e som',
          description: 'DJ, som e luz para eventos.',
          aliases: ['dj', 'som', 'musica', 'luzes'],
          commonPhrases: ['dj para festa', 'som para evento'],
          examples: ['preciso de dj'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['DJ e som'],
          sortOrder: 40,
        ),
        ServiceTaxonomySubcategory(
          id: 'event_planning',
          parentCategoryId: 'events',
          label: 'Organizacao de eventos',
          description: 'Planeamento, coordenacao e organizacao completa.',
          aliases: ['organizacao', 'planeamento', 'coordenacao', 'evento'],
          commonPhrases: ['organizar evento', 'planejar festa'],
          examples: ['organizador de casamento'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Organizacao de eventos'],
          sortOrder: 50,
        ),
      ],
    ),
    ServiceTaxonomyCategory(
      id: 'technology',
      label: 'Tecnologia',
      description: 'Telemoveis, computadores, internet e suporte informatico.',
      iconKey: 'technology',
      sortOrder: 60,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'phone_repair',
          parentCategoryId: 'technology',
          label: 'Reparacao de telemoveis',
          description: 'Ecras, baterias e pequenos problemas em telemoveis.',
          aliases: ['telemovel', 'telefone', 'ecra partido', 'bateria'],
          commonPhrases: ['arranjar telemovel', 'iphone partido'],
          examples: ['mudar ecra do telemovel'],
          allowedIntents: [ServiceIntent.now, ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Reparacao de telemoveis'],
          sortOrder: 10,
        ),
        ServiceTaxonomySubcategory(
          id: 'computer_repair',
          parentCategoryId: 'technology',
          label: 'Reparacao de computadores',
          description: 'Computadores lentos, formatacao e reparacoes.',
          aliases: ['computador', 'pc', 'portatil', 'virus'],
          commonPhrases: ['pc lento', 'computador lento', 'formatar pc'],
          examples: ['arranjar computador'],
          allowedIntents: [ServiceIntent.now, ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Reparacao de computadores'],
          sortOrder: 20,
        ),
        ServiceTaxonomySubcategory(
          id: 'it_support',
          parentCategoryId: 'technology',
          label: 'Suporte informatico',
          description: 'Configuracao de software, email e impressoras.',
          aliases: ['suporte informatico', 'tecnico', 'software', 'impressora'],
          commonPhrases: ['configurar email', 'instalar impressora'],
          examples: ['preciso de tecnico informatico'],
          allowedIntents: [ServiceIntent.now, ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Suporte informatico'],
          sortOrder: 30,
        ),
        ServiceTaxonomySubcategory(
          id: 'internet_router_setup',
          parentCategoryId: 'technology',
          label: 'Internet e routers',
          description: 'Wi-Fi, routers, internet e redes em casa.',
          aliases: ['internet', 'router', 'wifi', 'rede'],
          commonPhrases: ['configurar router', 'internet fraca'],
          examples: ['instalar internet em casa'],
          allowedIntents: [ServiceIntent.now, ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Configuracao de routers'],
          sortOrder: 40,
        ),
        ServiceTaxonomySubcategory(
          id: 'websites_apps',
          parentCategoryId: 'technology',
          label: 'Websites e apps',
          description: 'Sites, apps, lojas online e landing pages.',
          aliases: ['site', 'app', 'programador', 'loja online'],
          commonPhrases: ['criar site', 'fazer app'],
          examples: ['preciso de landing page'],
          allowedIntents: [ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Desenvolvimento digital'],
          sortOrder: 50,
        ),
      ],
    ),
    ServiceTaxonomyCategory(
      id: 'education',
      label: 'Educacao',
      description: 'Explicacoes, idiomas, musica e apoio escolar.',
      iconKey: 'education',
      sortOrder: 70,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'school_tutoring',
          parentCategoryId: 'education',
          label: 'Explicacoes',
          description: 'Apoio escolar e explicacoes por disciplina.',
          aliases: ['explicador', 'aulas', 'matematica', 'apoio escolar'],
          commonPhrases: ['aulas matematica', 'explicacoes matematica'],
          examples: ['preciso de explicacoes'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Explicacoes e formacao', 'Explicacoes de matematica'],
          sortOrder: 10,
        ),
        ServiceTaxonomySubcategory(
          id: 'languages',
          parentCategoryId: 'education',
          label: 'Idiomas',
          description: 'Aulas de linguas e conversacao.',
          aliases: ['idiomas', 'linguas', 'ingles', 'frances', 'aulas'],
          commonPhrases: ['aulas ingles', 'aprender idioma'],
          examples: ['professor de ingles'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Aulas de linguas'],
          sortOrder: 20,
        ),
        ServiceTaxonomySubcategory(
          id: 'music_lessons',
          parentCategoryId: 'education',
          label: 'Aulas de musica',
          description: 'Aulas de instrumentos, canto e teoria musical.',
          aliases: ['musica', 'guitarra', 'piano', 'canto', 'aulas'],
          commonPhrases: ['aulas guitarra', 'aulas de piano'],
          examples: ['professor de guitarra'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Aulas de musica', 'Aulas de guitarra'],
          sortOrder: 30,
        ),
        ServiceTaxonomySubcategory(
          id: 'school_support',
          parentCategoryId: 'education',
          label: 'Apoio escolar',
          description: 'Estudo acompanhado e trabalhos de casa.',
          aliases: ['estudo acompanhado', 'trabalhos de casa', 'testes'],
          commonPhrases: ['ajuda nos trabalhos de casa', 'preparar testes'],
          examples: ['apoio escolar semanal'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Apoio escolar'],
          sortOrder: 40,
        ),
        ServiceTaxonomySubcategory(
          id: 'programming_lessons',
          parentCategoryId: 'education',
          label: 'Aulas de programacao',
          description: 'Aulas de codigo, Python, Flutter e web.',
          aliases: ['programacao', 'codigo', 'python', 'flutter'],
          commonPhrases: ['aulas programacao', 'aprender codigo'],
          examples: ['explicacoes de javascript'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Aulas de programacao'],
          sortOrder: 50,
        ),
        ServiceTaxonomySubcategory(
          id: 'martial_arts',
          parentCategoryId: 'education',
          label: 'Artes marciais',
          description:
              'Aulas de karate, judo, defesa pessoal e modalidades semelhantes.',
          aliases: [
            'karate',
            'professor de karate',
            'artes marciais',
            'judo',
            'taekwondo',
            'jiu jitsu',
            'boxe',
            'capoeira',
            'defesa pessoal',
          ],
          commonPhrases: [
            'aulas de karate',
            'professor de karate',
            'aprender defesa pessoal',
            'aulas artes marciais',
          ],
          examples: [
            'quero aulas de karate',
            'professor de artes marciais para crianca',
          ],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: [],
          legacyNames: ['Aulas de karate', 'Artes marciais'],
          sortOrder: 60,
        ),
      ],
    ),
    ServiceTaxonomyCategory(
      id: 'transport_delivery',
      label: 'Transporte e entregas',
      description: 'Entregas, mudancas, objetos pesados e transfers.',
      iconKey: 'transport',
      sortOrder: 80,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'delivery',
          parentCategoryId: 'transport_delivery',
          label: 'Entregas',
          description: 'Recolha e entrega de objetos e encomendas.',
          aliases: ['entrega', 'recolha', 'estafeta', 'encomenda'],
          commonPhrases: ['levar encomenda', 'entrega urgente'],
          examples: ['preciso enviar uma encomenda'],
          allowedIntents: [ServiceIntent.now, ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.now,
          legacyServicoIds: const [],
          legacyNames: ['Entrega de encomendas'],
          sensitiveRequirementId: 'transport',
          riskLevel: CategoryRiskLevel.sensitive,
          requiresApproval: true,
          sortOrder: 10,
        ),
        ServiceTaxonomySubcategory(
          id: 'moving_help',
          parentCategoryId: 'transport_delivery',
          label: 'Mudancas',
          description: 'Mudancas de casa e ajuda com transporte.',
          aliases: ['mudanca', 'carrinha', 'transportar moveis'],
          commonPhrases: ['mover casa', 'ajuda mudanca'],
          examples: ['preciso de carrinha para mudanca'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Mudancas e entregas'],
          sortOrder: 20,
        ),
        ServiceTaxonomySubcategory(
          id: 'object_transport',
          parentCategoryId: 'transport_delivery',
          label: 'Transporte de objetos',
          description: 'Sofas, eletrodomesticos e objetos pesados.',
          aliases: ['sofa', 'frigorifico', 'objeto pesado', 'transporte'],
          commonPhrases: ['transportar sofa', 'levar frigorifico'],
          examples: ['transporte de maquina de lavar'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Transporte de moveis'],
          sortOrder: 30,
        ),
        ServiceTaxonomySubcategory(
          id: 'driver_transfer',
          parentCategoryId: 'transport_delivery',
          label: 'Motorista e transfer',
          description: 'Motorista, transfer e deslocacoes profissionais.',
          aliases: ['motorista', 'transfer', 'aeroporto', 'boleia'],
          commonPhrases: ['transfer aeroporto', 'motorista privado'],
          examples: ['preciso de motorista'],
          allowedIntents: [ServiceIntent.scheduled, ServiceIntent.quote],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Motorista'],
          sensitiveRequirementId: 'transport',
          riskLevel: CategoryRiskLevel.sensitive,
          requiresApproval: true,
          sortOrder: 40,
        ),
      ],
    ),
    ServiceTaxonomyCategory(
      id: 'care',
      label: 'Cuidados',
      description: 'Cuidados infantis, idosos e apoio domiciliario leve.',
      iconKey: 'care',
      sortOrder: 90,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'child_care',
          parentCategoryId: 'care',
          label: 'Cuidados infantis',
          description: 'Babysitter, ama e apoio a criancas.',
          aliases: ['babysitter', 'ama', 'crianca', 'cuidar crianca'],
          commonPhrases: ['buscar crianca na escola', 'cuidar de crianca'],
          examples: ['babysitter para noite'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: ['babysitter'],
          legacyNames: ['Babysitter'],
          sensitiveRequirementId: 'child_care',
          riskLevel: CategoryRiskLevel.sensitive,
          requiresApproval: true,
          sortOrder: 10,
        ),
        ServiceTaxonomySubcategory(
          id: 'elder_care',
          parentCategoryId: 'care',
          label: 'Cuidados a idosos',
          description: 'Acompanhamento e apoio a pessoas idosas.',
          aliases: ['idosos', 'cuidador idosos', 'acompanhante'],
          commonPhrases: ['apoio domiciliario', 'cuidar de idoso'],
          examples: ['acompanhante para idoso'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: ['cuidador_idosos'],
          legacyNames: ['Cuidador de idosos'],
          sensitiveRequirementId: 'elder_care',
          riskLevel: CategoryRiskLevel.sensitive,
          requiresApproval: true,
          sortOrder: 20,
        ),
        ServiceTaxonomySubcategory(
          id: 'home_support',
          parentCategoryId: 'care',
          label: 'Apoio domiciliario leve',
          description: 'Apoio simples em casa, sem cuidados clinicos.',
          aliases: ['apoio em casa', 'companhia', 'tarefas simples'],
          commonPhrases: ['ajuda em casa', 'companhia em casa'],
          examples: ['apoio domiciliario leve'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: const [],
          legacyNames: ['Apoio domiciliario'],
          sensitiveRequirementId: 'in_home_service',
          riskLevel: CategoryRiskLevel.sensitive,
          requiresApproval: true,
          sortOrder: 30,
        ),
      ],
    ),
    ServiceTaxonomyCategory(
      id: 'pets',
      label: 'Animais',
      description: 'Passeios, cuidados e higiene para animais.',
      iconKey: 'pets',
      sortOrder: 100,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'pet_care',
          parentCategoryId: 'pets',
          label: 'Cuidados de animais',
          description: 'Pet sitter, banho, tosa e cuidados gerais.',
          aliases: ['pet sitter', 'animais', 'banho', 'tosa'],
          commonPhrases: ['cuidar de animal', 'banho cao'],
          examples: ['pet sitter para ferias'],
          allowedIntents: [ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: ['pet_sitter'],
          legacyNames: ['Pet sitter', 'Cuidados para animais'],
          sortOrder: 10,
        ),
        ServiceTaxonomySubcategory(
          id: 'dog_walking',
          parentCategoryId: 'pets',
          label: 'Passeio de caes',
          description: 'Passeios pontuais ou regulares para caes.',
          aliases: ['dog walker', 'passeio cao', 'caes'],
          commonPhrases: ['passear cao', 'levar cao a rua'],
          examples: ['dog walker hoje'],
          allowedIntents: [ServiceIntent.now, ServiceIntent.scheduled],
          defaultIntent: ServiceIntent.scheduled,
          legacyServicoIds: ['dogwalker'],
          legacyNames: ['Dog walker'],
          sortOrder: 20,
        ),
      ],
    ),
    ServiceTaxonomyCategory(
      id: 'business_creative',
      label: 'Negocios e criativos',
      description: 'Design, conteudo, marketing e servicos criativos.',
      iconKey: 'creative',
      sortOrder: 110,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'graphic_design',
          parentCategoryId: 'business_creative',
          label: 'Design grafico',
          description: 'Logotipos, flyers, identidade e materiais digitais.',
          aliases: ['design', 'logo', 'logotipo', 'flyer'],
          commonPhrases: ['criar logotipo', 'fazer flyer'],
          examples: ['design para marca'],
          allowedIntents: [ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Criacao de logotipos', 'Design grafico'],
          sortOrder: 10,
        ),
        ServiceTaxonomySubcategory(
          id: 'illustration',
          parentCategoryId: 'business_creative',
          label: 'Ilustracao',
          description: 'Ilustracoes, retratos e arte digital.',
          aliases: ['ilustrador', 'ilustracao', 'retrato', 'arte'],
          commonPhrases: ['desenhar retrato', 'arte digital'],
          examples: ['retrato a lapis'],
          allowedIntents: [ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: ['retratista_lapis', 'caricaturista', 'ilustrador'],
          legacyNames: ['Retratista a lapis', 'Caricaturista', 'Ilustrador'],
          sortOrder: 20,
        ),
        ServiceTaxonomySubcategory(
          id: 'social_media',
          parentCategoryId: 'business_creative',
          label: 'Social media',
          description: 'Gestao de redes sociais e conteudo.',
          aliases: ['social media', 'instagram', 'facebook', 'conteudo'],
          commonPhrases: ['gerir instagram', 'posts redes sociais'],
          examples: ['social media para negocio'],
          allowedIntents: [ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Social media'],
          sortOrder: 30,
        ),
        ServiceTaxonomySubcategory(
          id: 'copywriting',
          parentCategoryId: 'business_creative',
          label: 'Copywriting',
          description: 'Textos, anuncios, paginas e conteudo comercial.',
          aliases: ['copywriting', 'texto', 'redacao', 'conteudo'],
          commonPhrases: ['texto para site', 'copy para anuncios'],
          examples: ['redator para landing page'],
          allowedIntents: [ServiceIntent.quote],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Copywriting'],
          sortOrder: 40,
        ),
      ],
    ),
    ServiceTaxonomyCategory(
      id: 'other',
      label: 'Outros',
      description: 'Servicos que ainda nao encaixam numa categoria principal.',
      iconKey: 'other',
      sortOrder: 120,
      subcategories: [
        ServiceTaxonomySubcategory(
          id: 'other_service',
          parentCategoryId: 'other',
          label: 'Outro servico',
          description: 'Pedido livre quando a categoria ainda nao esta clara.',
          aliases: ['outro', 'outros', 'servico diferente', 'nao sei'],
          commonPhrases: ['preciso de ajuda', 'servico nao listado'],
          examples: ['nao sei qual categoria escolher'],
          allowedIntents: [
            ServiceIntent.now,
            ServiceIntent.scheduled,
            ServiceIntent.quote,
          ],
          defaultIntent: ServiceIntent.quote,
          legacyServicoIds: const [],
          legacyNames: ['Outro servico'],
          sortOrder: 10,
        ),
      ],
    ),
  ];

  static List<ServiceTaxonomySubcategory> get subcategories {
    return categories
        .expand((category) => category.subcategories)
        .toList(growable: false);
  }

  static ServiceTaxonomyCategory? findCategoryById(String id) {
    final normalized = id.trim();
    for (final category in categories) {
      if (category.id == normalized) return category;
    }
    return null;
  }

  static ServiceTaxonomySubcategory? findSubcategoryById(String id) {
    final normalized = id.trim();
    for (final subcategory in subcategories) {
      if (subcategory.id == normalized) return subcategory;
    }
    return null;
  }

  static ServiceTaxonomySubcategory get otherSubcategory {
    return findSubcategoryById('other_service')!;
  }

  static ServiceTaxonomySubcategory? mapLegacyServicoToSubcategory(
    Servico servico,
  ) {
    final legacyId = servico.id.trim();
    final legacyName = ServiceTaxonomyNormalizer.normalize(servico.name);
    for (final subcategory in subcategories) {
      if (subcategory.legacyServicoIds.contains(legacyId)) {
        return subcategory;
      }
      final legacyNames = subcategory.legacyNames
          .map(ServiceTaxonomyNormalizer.normalize)
          .toSet();
      if (legacyNames.contains(legacyName)) {
        return subcategory;
      }
    }
    return null;
  }
}
